@REM pyuic5 --output=..\ActVib\VibViewWindow.py VibViewWindow.ui
@REM pyuic5 --output=..\ActVib\PlotDialog.py PlotDialog.ui
@REM pyuic5 --output=..\ActVib\UploadDialog.py UploadDialog.ui
@REM pyuic5 --output=..\ActVib\WorkdirDialog.py WorkdirDialog.ui
@REM pyuic5 --output=..\ActVib\IMUPanel.py IMUPanel.ui
@REM pyuic5 --output=..\ActVib\GeneratorPanel.py GeneratorPanel.ui
@REM pyuic5 --output=..\ActVib\PlotCfgPanel.py PlotCfgPanel.ui
@REM pyuic5 --output=..\ActVib\ControlPanel.py ControlPanel.ui
@REM pyuic5 --output=..\ActVib\ADCPanel.py ADCPanel.ui
pyside2-uic --output=..\ActVib\VibViewWindow.py VibViewWindow.ui
pyside2-uic --output=..\ActVib\PlotDialog.py PlotDialog.ui
pyside2-uic --output=..\ActVib\UploadDialog.py UploadDialog.ui
pyside2-uic --output=..\ActVib\WorkdirDialog.py WorkdirDialog.ui
pyside2-uic --output=..\ActVib\IMUPanel.py IMUPanel.ui
pyside2-uic --output=..\ActVib\GeneratorPanel.py GeneratorPanel.ui
pyside2-uic --output=..\ActVib\PlotCfgPanel.py PlotCfgPanel.ui
pyside2-uic --output=..\ActVib\ControlPanel.py ControlPanel.ui
pyside2-uic --output=..\ActVib\ADCPanel.py ADCPanel.ui
pyside2-uic --output=..\ActVib\PathModeling.py PathModeling.ui
pyside2-uic --output=..\ActVib\DataViewer.py DataViewer.ui
pyside2-uic --output=..\ActVib\PreDist.py PreDist.ui