# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ADCPanel.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ADCForm(object):
    def setupUi(self, ADCForm):
        ADCForm.setObjectName("ADCForm")
        ADCForm.resize(609, 85)
        self.verticalLayout = QtWidgets.QVBoxLayout(ADCForm)
        self.verticalLayout.setContentsMargins(2, 0, 2, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.adcframe = QtWidgets.QFrame(ADCForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.adcframe.sizePolicy().hasHeightForWidth())
        self.adcframe.setSizePolicy(sizePolicy)
        self.adcframe.setObjectName("adcframe")
        self.gridLayout = QtWidgets.QGridLayout(self.adcframe)
        self.gridLayout.setContentsMargins(10, 2, 8, 4)
        self.gridLayout.setHorizontalSpacing(5)
        self.gridLayout.setVerticalSpacing(3)
        self.gridLayout.setObjectName("gridLayout")
        self.checkADC1 = QtWidgets.QCheckBox(self.adcframe)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkADC1.sizePolicy().hasHeightForWidth())
        self.checkADC1.setSizePolicy(sizePolicy)
        self.checkADC1.setObjectName("checkADC1")
        self.gridLayout.addWidget(self.checkADC1, 0, 2, 1, 1)
        self.comboRate1115 = QtWidgets.QComboBox(self.adcframe)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboRate1115.sizePolicy().hasHeightForWidth())
        self.comboRate1115.setSizePolicy(sizePolicy)
        self.comboRate1115.setObjectName("comboRate1115")
        self.comboRate1115.addItem("")
        self.comboRate1115.addItem("")
        self.comboRate1115.addItem("")
        self.comboRate1115.addItem("")
        self.comboRate1115.addItem("")
        self.comboRate1115.addItem("")
        self.comboRate1115.addItem("")
        self.comboRate1115.addItem("")
        self.gridLayout.addWidget(self.comboRate1115, 1, 6, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.adcframe)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 0, 4, 2, 1)
        self.checkADC3 = QtWidgets.QCheckBox(self.adcframe)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkADC3.sizePolicy().hasHeightForWidth())
        self.checkADC3.setSizePolicy(sizePolicy)
        self.checkADC3.setObjectName("checkADC3")
        self.gridLayout.addWidget(self.checkADC3, 0, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.adcframe)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.checkADC4 = QtWidgets.QCheckBox(self.adcframe)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkADC4.sizePolicy().hasHeightForWidth())
        self.checkADC4.setSizePolicy(sizePolicy)
        self.checkADC4.setObjectName("checkADC4")
        self.gridLayout.addWidget(self.checkADC4, 1, 3, 1, 1)
        self.comboADCModel = QtWidgets.QComboBox(self.adcframe)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboADCModel.sizePolicy().hasHeightForWidth())
        self.comboADCModel.setSizePolicy(sizePolicy)
        self.comboADCModel.setObjectName("comboADCModel")
        self.comboADCModel.addItem("")
        self.comboADCModel.addItem("")
        self.gridLayout.addWidget(self.comboADCModel, 1, 0, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.adcframe)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_33.sizePolicy().hasHeightForWidth())
        self.label_33.setSizePolicy(sizePolicy)
        self.label_33.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_33.setObjectName("label_33")
        self.gridLayout.addWidget(self.label_33, 1, 5, 1, 1)
        self.checkADC2 = QtWidgets.QCheckBox(self.adcframe)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkADC2.sizePolicy().hasHeightForWidth())
        self.checkADC2.setSizePolicy(sizePolicy)
        self.checkADC2.setObjectName("checkADC2")
        self.gridLayout.addWidget(self.checkADC2, 1, 2, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.adcframe)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_30.sizePolicy().hasHeightForWidth())
        self.label_30.setSizePolicy(sizePolicy)
        self.label_30.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_30.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_30.setObjectName("label_30")
        self.gridLayout.addWidget(self.label_30, 0, 5, 1, 1)
        self.line = QtWidgets.QFrame(self.adcframe)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 0, 1, 2, 1)
        self.comboRate1015 = QtWidgets.QComboBox(self.adcframe)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboRate1015.sizePolicy().hasHeightForWidth())
        self.comboRate1015.setSizePolicy(sizePolicy)
        self.comboRate1015.setObjectName("comboRate1015")
        self.comboRate1015.addItem("")
        self.comboRate1015.addItem("")
        self.comboRate1015.addItem("")
        self.comboRate1015.addItem("")
        self.comboRate1015.addItem("")
        self.comboRate1015.addItem("")
        self.comboRate1015.addItem("")
        self.gridLayout.addWidget(self.comboRate1015, 1, 7, 1, 1)
        self.comboADCRange = QtWidgets.QComboBox(self.adcframe)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboADCRange.sizePolicy().hasHeightForWidth())
        self.comboADCRange.setSizePolicy(sizePolicy)
        self.comboADCRange.setObjectName("comboADCRange")
        self.comboADCRange.addItem("")
        self.comboADCRange.addItem("")
        self.comboADCRange.addItem("")
        self.comboADCRange.addItem("")
        self.comboADCRange.addItem("")
        self.comboADCRange.addItem("")
        self.gridLayout.addWidget(self.comboADCRange, 0, 6, 1, 2)
        self.verticalLayout.addWidget(self.adcframe)

        self.retranslateUi(ADCForm)
        QtCore.QMetaObject.connectSlotsByName(ADCForm)

    def retranslateUi(self, ADCForm):
        _translate = QtCore.QCoreApplication.translate
        ADCForm.setWindowTitle(_translate("ADCForm", "Form"))
        self.checkADC1.setText(_translate("ADCForm", "Channel 1"))
        self.comboRate1115.setItemText(0, _translate("ADCForm", "8 SPS"))
        self.comboRate1115.setItemText(1, _translate("ADCForm", "16 SPS"))
        self.comboRate1115.setItemText(2, _translate("ADCForm", "32 SPS"))
        self.comboRate1115.setItemText(3, _translate("ADCForm", "64 SPS"))
        self.comboRate1115.setItemText(4, _translate("ADCForm", "128 SPS"))
        self.comboRate1115.setItemText(5, _translate("ADCForm", "250 SPS"))
        self.comboRate1115.setItemText(6, _translate("ADCForm", "475 SPS"))
        self.comboRate1115.setItemText(7, _translate("ADCForm", "860 SPS"))
        self.checkADC3.setText(_translate("ADCForm", "Channel 3"))
        self.label.setText(_translate("ADCForm", "Model:"))
        self.checkADC4.setText(_translate("ADCForm", "Channel 4"))
        self.comboADCModel.setItemText(0, _translate("ADCForm", "ADS1115"))
        self.comboADCModel.setItemText(1, _translate("ADCForm", "ADS1015"))
        self.label_33.setText(_translate("ADCForm", "Rate:"))
        self.checkADC2.setText(_translate("ADCForm", "Channel 2"))
        self.label_30.setText(_translate("ADCForm", "Range:"))
        self.comboRate1015.setItemText(0, _translate("ADCForm", "128 SPS"))
        self.comboRate1015.setItemText(1, _translate("ADCForm", "250 SPS"))
        self.comboRate1015.setItemText(2, _translate("ADCForm", "490 SPS"))
        self.comboRate1015.setItemText(3, _translate("ADCForm", "920 SPS"))
        self.comboRate1015.setItemText(4, _translate("ADCForm", "1600 SPS"))
        self.comboRate1015.setItemText(5, _translate("ADCForm", "2400 SPS"))
        self.comboRate1015.setItemText(6, _translate("ADCForm", "3300 SPS"))
        self.comboADCRange.setItemText(0, _translate("ADCForm", "±6,144 V"))
        self.comboADCRange.setItemText(1, _translate("ADCForm", "±4,096 V"))
        self.comboADCRange.setItemText(2, _translate("ADCForm", "±2,048 V"))
        self.comboADCRange.setItemText(3, _translate("ADCForm", "±1,024 V"))
        self.comboADCRange.setItemText(4, _translate("ADCForm", "±0,512 V"))
        self.comboADCRange.setItemText(5, _translate("ADCForm", "±0,256 V"))
