# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ControlPanel.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ControlForm(object):
    def setupUi(self, ControlForm):
        ControlForm.setObjectName("ControlForm")
        ControlForm.resize(481, 190)
        self.horizontalLayout = QtWidgets.QHBoxLayout(ControlForm)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Controle = QtWidgets.QFrame(ControlForm)
        self.Controle.setAutoFillBackground(False)
        self.Controle.setStyleSheet("")
        self.Controle.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Controle.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Controle.setLineWidth(0)
        self.Controle.setObjectName("Controle")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.Controle)
        self.horizontalLayout_5.setContentsMargins(5, 5, 0, 5)
        self.horizontalLayout_5.setSpacing(2)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.checkControle = QtWidgets.QCheckBox(self.Controle)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkControle.sizePolicy().hasHeightForWidth())
        self.checkControle.setSizePolicy(sizePolicy)
        self.checkControle.setObjectName("checkControle")
        self.horizontalLayout_5.addWidget(self.checkControle)
        self.line = QtWidgets.QFrame(self.Controle)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_5.addWidget(self.line)
        self.frame_7 = QtWidgets.QFrame(self.Controle)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_7.sizePolicy().hasHeightForWidth())
        self.frame_7.setSizePolicy(sizePolicy)
        self.frame_7.setMinimumSize(QtCore.QSize(0, 150))
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_7.setLineWidth(0)
        self.frame_7.setObjectName("frame_7")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_7)
        self.gridLayout_2.setContentsMargins(3, 1, 5, 1)
        self.gridLayout_2.setVerticalSpacing(2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_11 = QtWidgets.QLabel(self.frame_7)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 8, 5, 1, 2)
        self.checkAlgOn = QtWidgets.QCheckBox(self.frame_7)
        self.checkAlgOn.setObjectName("checkAlgOn")
        self.gridLayout_2.addWidget(self.checkAlgOn, 4, 4, 1, 2)
        self.spinTAlgOn = QtWidgets.QSpinBox(self.frame_7)
        self.spinTAlgOn.setObjectName("spinTAlgOn")
        self.gridLayout_2.addWidget(self.spinTAlgOn, 4, 6, 1, 1)
        self.comboIMURef = QtWidgets.QComboBox(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboIMURef.sizePolicy().hasHeightForWidth())
        self.comboIMURef.setSizePolicy(sizePolicy)
        self.comboIMURef.setObjectName("comboIMURef")
        self.comboIMURef.addItem("")
        self.comboIMURef.addItem("")
        self.comboIMURef.addItem("")
        self.gridLayout_2.addWidget(self.comboIMURef, 2, 4, 1, 3)
        self.normCtrl = QtWidgets.QLineEdit(self.frame_7)
        self.normCtrl.setObjectName("normCtrl")
        self.gridLayout_2.addWidget(self.normCtrl, 8, 7, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.frame_7)
        self.label_17.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 3, 3, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 4, 3, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_24.sizePolicy().hasHeightForWidth())
        self.label_24.setSizePolicy(sizePolicy)
        self.label_24.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_24.setObjectName("label_24")
        self.gridLayout_2.addWidget(self.label_24, 0, 3, 1, 1)
        self.label_48 = QtWidgets.QLabel(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_48.sizePolicy().hasHeightForWidth())
        self.label_48.setSizePolicy(sizePolicy)
        self.label_48.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_48.setObjectName("label_48")
        self.gridLayout_2.addWidget(self.label_48, 1, 3, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.frame_7)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_2.addWidget(self.line_3, 5, 4, 4, 1)
        self.label_16 = QtWidgets.QLabel(self.frame_7)
        self.label_16.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_2.addWidget(self.label_16, 2, 3, 1, 1)
        self.comboIMUError = QtWidgets.QComboBox(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboIMUError.sizePolicy().hasHeightForWidth())
        self.comboIMUError.setSizePolicy(sizePolicy)
        self.comboIMUError.setObjectName("comboIMUError")
        self.comboIMUError.addItem("")
        self.comboIMUError.addItem("")
        self.comboIMUError.addItem("")
        self.gridLayout_2.addWidget(self.comboIMUError, 3, 4, 1, 3)
        self.spinMemCtrl = QtWidgets.QSpinBox(self.frame_7)
        self.spinMemCtrl.setMinimum(1)
        self.spinMemCtrl.setMaximum(3000)
        self.spinMemCtrl.setProperty("value", 100)
        self.spinMemCtrl.setObjectName("spinMemCtrl")
        self.gridLayout_2.addWidget(self.spinMemCtrl, 6, 7, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 7, 5, 1, 2)
        self.comboControlChannel = QtWidgets.QComboBox(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboControlChannel.sizePolicy().hasHeightForWidth())
        self.comboControlChannel.setSizePolicy(sizePolicy)
        self.comboControlChannel.setObjectName("comboControlChannel")
        self.comboControlChannel.addItem("")
        self.comboControlChannel.addItem("")
        self.comboControlChannel.addItem("")
        self.comboControlChannel.addItem("")
        self.gridLayout_2.addWidget(self.comboControlChannel, 1, 4, 1, 4)
        self.comboRef = QtWidgets.QComboBox(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboRef.sizePolicy().hasHeightForWidth())
        self.comboRef.setSizePolicy(sizePolicy)
        self.comboRef.setObjectName("comboRef")
        self.comboRef.addItem("")
        self.comboRef.addItem("")
        self.comboRef.addItem("")
        self.comboRef.addItem("")
        self.comboRef.addItem("")
        self.comboRef.addItem("")
        self.gridLayout_2.addWidget(self.comboRef, 2, 7, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.frame_7)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 6, 5, 1, 2)
        self.comboErro = QtWidgets.QComboBox(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboErro.sizePolicy().hasHeightForWidth())
        self.comboErro.setSizePolicy(sizePolicy)
        self.comboErro.setObjectName("comboErro")
        self.comboErro.addItem("")
        self.comboErro.addItem("")
        self.comboErro.addItem("")
        self.comboErro.addItem("")
        self.comboErro.addItem("")
        self.comboErro.addItem("")
        self.gridLayout_2.addWidget(self.comboErro, 3, 7, 1, 1)
        self.comboAlgoritmo = QtWidgets.QComboBox(self.frame_7)
        self.comboAlgoritmo.setObjectName("comboAlgoritmo")
        self.comboAlgoritmo.addItem("")
        self.comboAlgoritmo.addItem("")
        self.comboAlgoritmo.addItem("")
        self.gridLayout_2.addWidget(self.comboAlgoritmo, 4, 7, 1, 1)
        self.passoCtrl = QtWidgets.QLineEdit(self.frame_7)
        self.passoCtrl.setObjectName("passoCtrl")
        self.gridLayout_2.addWidget(self.passoCtrl, 7, 7, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.frame_7)
        self.label_10.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 6, 3, 3, 1)
        self.comboPerturbChannel = QtWidgets.QComboBox(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboPerturbChannel.sizePolicy().hasHeightForWidth())
        self.comboPerturbChannel.setSizePolicy(sizePolicy)
        self.comboPerturbChannel.setObjectName("comboPerturbChannel")
        self.comboPerturbChannel.addItem("")
        self.comboPerturbChannel.addItem("")
        self.comboPerturbChannel.addItem("")
        self.comboPerturbChannel.addItem("")
        self.gridLayout_2.addWidget(self.comboPerturbChannel, 0, 4, 1, 4)
        self.horizontalLayout_5.addWidget(self.frame_7)
        self.line_4 = QtWidgets.QFrame(self.Controle)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout_5.addWidget(self.line_4)
        self.horizontalLayout.addWidget(self.Controle)

        self.retranslateUi(ControlForm)
        QtCore.QMetaObject.connectSlotsByName(ControlForm)
        ControlForm.setTabOrder(self.checkControle, self.comboPerturbChannel)
        ControlForm.setTabOrder(self.comboPerturbChannel, self.comboControlChannel)
        ControlForm.setTabOrder(self.comboControlChannel, self.comboIMURef)
        ControlForm.setTabOrder(self.comboIMURef, self.comboRef)
        ControlForm.setTabOrder(self.comboRef, self.comboIMUError)
        ControlForm.setTabOrder(self.comboIMUError, self.comboErro)
        ControlForm.setTabOrder(self.comboErro, self.checkAlgOn)
        ControlForm.setTabOrder(self.checkAlgOn, self.spinTAlgOn)
        ControlForm.setTabOrder(self.spinTAlgOn, self.comboAlgoritmo)
        ControlForm.setTabOrder(self.comboAlgoritmo, self.spinMemCtrl)
        ControlForm.setTabOrder(self.spinMemCtrl, self.passoCtrl)
        ControlForm.setTabOrder(self.passoCtrl, self.normCtrl)

    def retranslateUi(self, ControlForm):
        _translate = QtCore.QCoreApplication.translate
        ControlForm.setWindowTitle(_translate("ControlForm", "Form"))
        self.checkControle.setText(_translate("ControlForm", "Enable"))
        self.label_11.setText(_translate("ControlForm", "Penalization:"))
        self.checkAlgOn.setText(_translate("ControlForm", "On ≥"))
        self.comboIMURef.setItemText(0, _translate("ControlForm", "IMU 1"))
        self.comboIMURef.setItemText(1, _translate("ControlForm", "IMU 2"))
        self.comboIMURef.setItemText(2, _translate("ControlForm", "IMU 3"))
        self.normCtrl.setText(_translate("ControlForm", "1e-4"))
        self.label_17.setText(_translate("ControlForm", "Error Sensor:"))
        self.label_8.setText(_translate("ControlForm", "Algorithm:"))
        self.label_24.setText(_translate("ControlForm", "Perturbation:"))
        self.label_48.setText(_translate("ControlForm", "Control:"))
        self.label_16.setText(_translate("ControlForm", "Ref. Sensor:"))
        self.comboIMUError.setItemText(0, _translate("ControlForm", "IMU 1"))
        self.comboIMUError.setItemText(1, _translate("ControlForm", "IMU 2"))
        self.comboIMUError.setItemText(2, _translate("ControlForm", "IMU 3"))
        self.label_9.setText(_translate("ControlForm", "Step size:"))
        self.comboControlChannel.setCurrentText(_translate("ControlForm", "Output 1"))
        self.comboControlChannel.setItemText(0, _translate("ControlForm", "Output 1"))
        self.comboControlChannel.setItemText(1, _translate("ControlForm", "Output 2"))
        self.comboControlChannel.setItemText(2, _translate("ControlForm", "Output 3"))
        self.comboControlChannel.setItemText(3, _translate("ControlForm", "Output 4"))
        self.comboRef.setItemText(0, _translate("ControlForm", "X-Axis Accelerometer"))
        self.comboRef.setItemText(1, _translate("ControlForm", "Y-Axis Accelerometer"))
        self.comboRef.setItemText(2, _translate("ControlForm", "Z-Axis Accelerometer"))
        self.comboRef.setItemText(3, _translate("ControlForm", "X-Axis Gyro"))
        self.comboRef.setItemText(4, _translate("ControlForm", "Y-Axis Gyro"))
        self.comboRef.setItemText(5, _translate("ControlForm", "Z-Axis Gyro"))
        self.label_12.setText(_translate("ControlForm", "Memory size:"))
        self.comboErro.setItemText(0, _translate("ControlForm", "X-Axis Accelerometer"))
        self.comboErro.setItemText(1, _translate("ControlForm", "Y-Axis Accelerometer"))
        self.comboErro.setItemText(2, _translate("ControlForm", "Z-Axis Accelerometer"))
        self.comboErro.setItemText(3, _translate("ControlForm", "X-Axis Gyro"))
        self.comboErro.setItemText(4, _translate("ControlForm", "Y-Axis Gyro"))
        self.comboErro.setItemText(5, _translate("ControlForm", "Z-Axis Gyro"))
        self.comboAlgoritmo.setItemText(0, _translate("ControlForm", "FxNLMS"))
        self.comboAlgoritmo.setItemText(1, _translate("ControlForm", "FxLMS"))
        self.comboAlgoritmo.setItemText(2, _translate("ControlForm", "FxNLMS Modificado Proposto"))
        self.passoCtrl.setText(_translate("ControlForm", "0.01"))
        self.label_10.setText(_translate("ControlForm", "Parameters:"))
        self.comboPerturbChannel.setItemText(0, _translate("ControlForm", "Output 1"))
        self.comboPerturbChannel.setItemText(1, _translate("ControlForm", "Output 2"))
        self.comboPerturbChannel.setItemText(2, _translate("ControlForm", "Output 3"))
        self.comboPerturbChannel.setItemText(3, _translate("ControlForm", "Output 4"))
