# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GeneratorPanel.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GeneratorPanel(object):
    def setupUi(self, GeneratorPanel):
        GeneratorPanel.setObjectName("GeneratorPanel")
        GeneratorPanel.resize(548, 79)
        self.verticalLayout = QtWidgets.QVBoxLayout(GeneratorPanel)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_4 = QtWidgets.QFrame(GeneratorPanel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_4.setLineWidth(0)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_6.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_6.setSpacing(5)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.checkEnable = QtWidgets.QCheckBox(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkEnable.sizePolicy().hasHeightForWidth())
        self.checkEnable.setSizePolicy(sizePolicy)
        self.checkEnable.setCheckable(True)
        self.checkEnable.setChecked(True)
        self.checkEnable.setObjectName("checkEnable")
        self.horizontalLayout_6.addWidget(self.checkEnable)
        self.comboType = QtWidgets.QComboBox(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboType.sizePolicy().hasHeightForWidth())
        self.comboType.setSizePolicy(sizePolicy)
        self.comboType.setObjectName("comboType")
        self.comboType.addItem("")
        self.comboType.addItem("")
        self.comboType.addItem("")
        self.comboType.addItem("")
        self.horizontalLayout_6.addWidget(self.comboType)
        self.label_2 = QtWidgets.QLabel(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_6.addWidget(self.label_2)
        self.spinAmpl = QtWidgets.QDoubleSpinBox(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinAmpl.sizePolicy().hasHeightForWidth())
        self.spinAmpl.setSizePolicy(sizePolicy)
        self.spinAmpl.setDecimals(3)
        self.spinAmpl.setMaximum(1.0)
        self.spinAmpl.setSingleStep(0.1)
        self.spinAmpl.setProperty("value", 0.0)
        self.spinAmpl.setObjectName("spinAmpl")
        self.horizontalLayout_6.addWidget(self.spinAmpl)
        self.label_3 = QtWidgets.QLabel(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_6.addWidget(self.label_3)
        self.spinFreq = QtWidgets.QDoubleSpinBox(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinFreq.sizePolicy().hasHeightForWidth())
        self.spinFreq.setSizePolicy(sizePolicy)
        self.spinFreq.setMaximum(100.0)
        self.spinFreq.setSingleStep(0.1)
        self.spinFreq.setProperty("value", 10.0)
        self.spinFreq.setObjectName("spinFreq")
        self.horizontalLayout_6.addWidget(self.spinFreq)
        self.verticalLayout.addWidget(self.frame_4)
        self.extrasCanal1 = QtWidgets.QFrame(GeneratorPanel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.extrasCanal1.sizePolicy().hasHeightForWidth())
        self.extrasCanal1.setSizePolicy(sizePolicy)
        self.extrasCanal1.setMinimumSize(QtCore.QSize(0, 0))
        self.extrasCanal1.setAutoFillBackground(False)
        self.extrasCanal1.setStyleSheet("")
        self.extrasCanal1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.extrasCanal1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.extrasCanal1.setLineWidth(0)
        self.extrasCanal1.setObjectName("extrasCanal1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.extrasCanal1)
        self.horizontalLayout_2.setContentsMargins(2, 1, 0, 1)
        self.horizontalLayout_2.setSpacing(3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_26 = QtWidgets.QLabel(self.extrasCanal1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_26.sizePolicy().hasHeightForWidth())
        self.label_26.setSizePolicy(sizePolicy)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_2.addWidget(self.label_26)
        self.chirpA2 = QtWidgets.QDoubleSpinBox(self.extrasCanal1)
        self.chirpA2.setDecimals(3)
        self.chirpA2.setMaximum(1.0)
        self.chirpA2.setSingleStep(0.1)
        self.chirpA2.setObjectName("chirpA2")
        self.horizontalLayout_2.addWidget(self.chirpA2)
        self.label_19 = QtWidgets.QLabel(self.extrasCanal1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_2.addWidget(self.label_19)
        self.chirpTinicio = QtWidgets.QSpinBox(self.extrasCanal1)
        self.chirpTinicio.setMaximum(255)
        self.chirpTinicio.setProperty("value", 10)
        self.chirpTinicio.setObjectName("chirpTinicio")
        self.horizontalLayout_2.addWidget(self.chirpTinicio)
        self.label_18 = QtWidgets.QLabel(self.extrasCanal1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_2.addWidget(self.label_18)
        self.chirpDeltaI = QtWidgets.QDoubleSpinBox(self.extrasCanal1)
        self.chirpDeltaI.setDecimals(1)
        self.chirpDeltaI.setMinimum(0.1)
        self.chirpDeltaI.setMaximum(25.5)
        self.chirpDeltaI.setSingleStep(1.0)
        self.chirpDeltaI.setProperty("value", 10.0)
        self.chirpDeltaI.setObjectName("chirpDeltaI")
        self.horizontalLayout_2.addWidget(self.chirpDeltaI)
        self.label_20 = QtWidgets.QLabel(self.extrasCanal1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_2.addWidget(self.label_20)
        self.chirpTfim = QtWidgets.QSpinBox(self.extrasCanal1)
        self.chirpTfim.setMaximum(255)
        self.chirpTfim.setProperty("value", 100)
        self.chirpTfim.setObjectName("chirpTfim")
        self.horizontalLayout_2.addWidget(self.chirpTfim)
        self.label_25 = QtWidgets.QLabel(self.extrasCanal1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_25.sizePolicy().hasHeightForWidth())
        self.label_25.setSizePolicy(sizePolicy)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_2.addWidget(self.label_25)
        self.chirpDeltaF = QtWidgets.QDoubleSpinBox(self.extrasCanal1)
        self.chirpDeltaF.setDecimals(1)
        self.chirpDeltaF.setMinimum(0.1)
        self.chirpDeltaF.setMaximum(25.5)
        self.chirpDeltaF.setProperty("value", 10.0)
        self.chirpDeltaF.setObjectName("chirpDeltaF")
        self.horizontalLayout_2.addWidget(self.chirpDeltaF)
        self.verticalLayout.addWidget(self.extrasCanal1)

        self.retranslateUi(GeneratorPanel)
        self.comboType.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(GeneratorPanel)

    def retranslateUi(self, GeneratorPanel):
        _translate = QtCore.QCoreApplication.translate
        GeneratorPanel.setWindowTitle(_translate("GeneratorPanel", "Form"))
        self.checkEnable.setText(_translate("GeneratorPanel", "Enable"))
        self.comboType.setItemText(0, _translate("GeneratorPanel", "Noise"))
        self.comboType.setItemText(1, _translate("GeneratorPanel", "Harmonic"))
        self.comboType.setItemText(2, _translate("GeneratorPanel", "Chirp"))
        self.comboType.setItemText(3, _translate("GeneratorPanel", "Step"))
        self.label_2.setText(_translate("GeneratorPanel", "Ampl.:"))
        self.label_3.setText(_translate("GeneratorPanel", "Freq.:"))
        self.label_26.setText(_translate("GeneratorPanel", "A2:"))
        self.label_19.setText(_translate("GeneratorPanel", "ST:"))
        self.label_18.setText(_translate("GeneratorPanel", "DI:"))
        self.label_20.setText(_translate("GeneratorPanel", "FT:"))
        self.label_25.setText(_translate("GeneratorPanel", "DF:"))
