# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'IMUPanel.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_IMUPanel(object):
    def setupUi(self, IMUPanel):
        IMUPanel.setObjectName("IMUPanel")
        IMUPanel.resize(585, 49)
        self.verticalLayout = QtWidgets.QVBoxLayout(IMUPanel)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.imuframe = QtWidgets.QFrame(IMUPanel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imuframe.sizePolicy().hasHeightForWidth())
        self.imuframe.setSizePolicy(sizePolicy)
        self.imuframe.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.imuframe.setFrameShadow(QtWidgets.QFrame.Plain)
        self.imuframe.setLineWidth(0)
        self.imuframe.setObjectName("imuframe")
        self.gridLayout = QtWidgets.QGridLayout(self.imuframe)
        self.gridLayout.setContentsMargins(3, 2, 3, 2)
        self.gridLayout.setHorizontalSpacing(6)
        self.gridLayout.setVerticalSpacing(1)
        self.gridLayout.setObjectName("gridLayout")
        self.comboAddress = QtWidgets.QComboBox(self.imuframe)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboAddress.sizePolicy().hasHeightForWidth())
        self.comboAddress.setSizePolicy(sizePolicy)
        self.comboAddress.setMinimumSize(QtCore.QSize(0, 0))
        self.comboAddress.setBaseSize(QtCore.QSize(0, 0))
        self.comboAddress.setObjectName("comboAddress")
        self.comboAddress.addItem("")
        self.comboAddress.addItem("")
        self.comboAddress.addItem("")
        self.comboAddress.addItem("")
        self.comboAddress.addItem("")
        self.comboAddress.addItem("")
        self.gridLayout.addWidget(self.comboAddress, 3, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.imuframe)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 3, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.imuframe)
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 1, 6, 1, 1)
        self.comboType = QtWidgets.QComboBox(self.imuframe)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboType.sizePolicy().hasHeightForWidth())
        self.comboType.setSizePolicy(sizePolicy)
        self.comboType.setObjectName("comboType")
        self.comboType.addItem("")
        self.comboType.addItem("")
        self.comboType.addItem("")
        self.gridLayout.addWidget(self.comboType, 1, 0, 1, 2)
        self.label_15 = QtWidgets.QLabel(self.imuframe)
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 3, 6, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.imuframe)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 3, 3, 1, 1)
        self.comboFilter = QtWidgets.QComboBox(self.imuframe)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboFilter.sizePolicy().hasHeightForWidth())
        self.comboFilter.setSizePolicy(sizePolicy)
        self.comboFilter.setObjectName("comboFilter")
        self.comboFilter.addItem("")
        self.comboFilter.addItem("")
        self.comboFilter.addItem("")
        self.comboFilter.addItem("")
        self.comboFilter.addItem("")
        self.comboFilter.addItem("")
        self.comboFilter.addItem("")
        self.gridLayout.addWidget(self.comboFilter, 3, 7, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.imuframe)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 1, 2, 4, 1)
        self.line = QtWidgets.QFrame(self.imuframe)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 1, 5, 4, 1)
        self.comboAccRange = QtWidgets.QComboBox(self.imuframe)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboAccRange.sizePolicy().hasHeightForWidth())
        self.comboAccRange.setSizePolicy(sizePolicy)
        self.comboAccRange.setObjectName("comboAccRange")
        self.comboAccRange.addItem("")
        self.comboAccRange.addItem("")
        self.comboAccRange.addItem("")
        self.comboAccRange.addItem("")
        self.gridLayout.addWidget(self.comboAccRange, 3, 4, 1, 1)
        self.comboGyroRange = QtWidgets.QComboBox(self.imuframe)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboGyroRange.sizePolicy().hasHeightForWidth())
        self.comboGyroRange.setSizePolicy(sizePolicy)
        self.comboGyroRange.setObjectName("comboGyroRange")
        self.comboGyroRange.addItem("")
        self.comboGyroRange.addItem("")
        self.comboGyroRange.addItem("")
        self.comboGyroRange.addItem("")
        self.comboGyroRange.addItem("")
        self.gridLayout.addWidget(self.comboGyroRange, 1, 7, 1, 2)
        self.comboFilter2 = QtWidgets.QComboBox(self.imuframe)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboFilter2.sizePolicy().hasHeightForWidth())
        self.comboFilter2.setSizePolicy(sizePolicy)
        self.comboFilter2.setObjectName("comboFilter2")
        self.comboFilter2.addItem("")
        self.comboFilter2.addItem("")
        self.comboFilter2.addItem("")
        self.comboFilter2.addItem("")
        self.gridLayout.addWidget(self.comboFilter2, 3, 8, 1, 1)
        self.comboBus = QtWidgets.QComboBox(self.imuframe)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBus.sizePolicy().hasHeightForWidth())
        self.comboBus.setSizePolicy(sizePolicy)
        self.comboBus.setBaseSize(QtCore.QSize(30, 0))
        self.comboBus.setObjectName("comboBus")
        self.comboBus.addItem("")
        self.comboBus.addItem("")
        self.comboBus.addItem("")
        self.gridLayout.addWidget(self.comboBus, 1, 4, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.imuframe)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 3, 1, 1)
        self.verticalLayout.addWidget(self.imuframe)

        self.retranslateUi(IMUPanel)
        QtCore.QMetaObject.connectSlotsByName(IMUPanel)
        IMUPanel.setTabOrder(self.comboType, self.comboAddress)
        IMUPanel.setTabOrder(self.comboAddress, self.comboBus)
        IMUPanel.setTabOrder(self.comboBus, self.comboAccRange)
        IMUPanel.setTabOrder(self.comboAccRange, self.comboGyroRange)
        IMUPanel.setTabOrder(self.comboGyroRange, self.comboFilter)
        IMUPanel.setTabOrder(self.comboFilter, self.comboFilter2)

    def retranslateUi(self, IMUPanel):
        _translate = QtCore.QCoreApplication.translate
        IMUPanel.setWindowTitle(_translate("IMUPanel", "Form"))
        self.comboAddress.setItemText(0, _translate("IMUPanel", "0x68"))
        self.comboAddress.setItemText(1, _translate("IMUPanel", "0x69"))
        self.comboAddress.setItemText(2, _translate("IMUPanel", "0x6A"))
        self.comboAddress.setItemText(3, _translate("IMUPanel", "0x6B"))
        self.comboAddress.setItemText(4, _translate("IMUPanel", "CS5"))
        self.comboAddress.setItemText(5, _translate("IMUPanel", "CS33"))
        self.label.setText(_translate("IMUPanel", "Addr:"))
        self.label_14.setText(_translate("IMUPanel", "GyroR:"))
        self.comboType.setItemText(0, _translate("IMUPanel", "Disabled"))
        self.comboType.setItemText(1, _translate("IMUPanel", "MPU6050"))
        self.comboType.setItemText(2, _translate("IMUPanel", "LSM6DS3"))
        self.label_15.setText(_translate("IMUPanel", "Filter:"))
        self.label_13.setText(_translate("IMUPanel", "AccR:"))
        self.comboFilter.setItemText(0, _translate("IMUPanel", "260Hz"))
        self.comboFilter.setItemText(1, _translate("IMUPanel", "184Hz"))
        self.comboFilter.setItemText(2, _translate("IMUPanel", "94Hz"))
        self.comboFilter.setItemText(3, _translate("IMUPanel", "44Hz"))
        self.comboFilter.setItemText(4, _translate("IMUPanel", "21Hz"))
        self.comboFilter.setItemText(5, _translate("IMUPanel", "10Hz"))
        self.comboFilter.setItemText(6, _translate("IMUPanel", "6Hz"))
        self.comboAccRange.setItemText(0, _translate("IMUPanel", "±2g (±19,6m/s²)"))
        self.comboAccRange.setItemText(1, _translate("IMUPanel", "±4g (±39,2m/s²)"))
        self.comboAccRange.setItemText(2, _translate("IMUPanel", "±8g (±78,4m/s²)"))
        self.comboAccRange.setItemText(3, _translate("IMUPanel", "±16g (±156,9m/s²)"))
        self.comboGyroRange.setItemText(0, _translate("IMUPanel", "±125º/s"))
        self.comboGyroRange.setItemText(1, _translate("IMUPanel", "±250º/s"))
        self.comboGyroRange.setItemText(2, _translate("IMUPanel", "±500º/s"))
        self.comboGyroRange.setItemText(3, _translate("IMUPanel", "±1000º/s"))
        self.comboGyroRange.setItemText(4, _translate("IMUPanel", "±2000º/s"))
        self.comboFilter2.setItemText(0, _translate("IMUPanel", "400Hz"))
        self.comboFilter2.setItemText(1, _translate("IMUPanel", "200Hz"))
        self.comboFilter2.setItemText(2, _translate("IMUPanel", "100Hz"))
        self.comboFilter2.setItemText(3, _translate("IMUPanel", "50Hz"))
        self.comboBus.setItemText(0, _translate("IMUPanel", "I2C-1"))
        self.comboBus.setItemText(1, _translate("IMUPanel", "I2C-2"))
        self.comboBus.setItemText(2, _translate("IMUPanel", "VSPI"))
        self.label_2.setText(_translate("IMUPanel", "Bus:"))
