# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VibViewWindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1090, 732)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setLineWidth(0)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.label_4 = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.elapsedTime = QtWidgets.QLabel(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.elapsedTime.sizePolicy().hasHeightForWidth())
        self.elapsedTime.setSizePolicy(sizePolicy)
        self.elapsedTime.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.elapsedTime.setFont(font)
        self.elapsedTime.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.elapsedTime.setLineWidth(2)
        self.elapsedTime.setAlignment(QtCore.Qt.AlignCenter)
        self.elapsedTime.setObjectName("elapsedTime")
        self.horizontalLayout_3.addWidget(self.elapsedTime)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.label_5 = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.controlTime = QtWidgets.QLabel(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.controlTime.sizePolicy().hasHeightForWidth())
        self.controlTime.setSizePolicy(sizePolicy)
        self.controlTime.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.controlTime.setFont(font)
        self.controlTime.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.controlTime.setAlignment(QtCore.Qt.AlignCenter)
        self.controlTime.setObjectName("controlTime")
        self.horizontalLayout_3.addWidget(self.controlTime)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.label_6 = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        self.sampleTime = QtWidgets.QLabel(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sampleTime.sizePolicy().hasHeightForWidth())
        self.sampleTime.setSizePolicy(sizePolicy)
        self.sampleTime.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.sampleTime.setFont(font)
        self.sampleTime.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sampleTime.setAlignment(QtCore.Qt.AlignCenter)
        self.sampleTime.setObjectName("sampleTime")
        self.horizontalLayout_3.addWidget(self.sampleTime)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.verticalLayout.addWidget(self.frame_3)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setLineWidth(0)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(3, 0, 3, 0)
        self.horizontalLayout.setSpacing(4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame1 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame1.sizePolicy().hasHeightForWidth())
        self.frame1.setSizePolicy(sizePolicy)
        self.frame1.setObjectName("frame1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame1)
        self.verticalLayout_2.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_2.setSpacing(3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.frame1)
        self.tabWidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setBaseSize(QtCore.QSize(0, 0))
        self.tabWidget.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.tabWidget.setElideMode(QtCore.Qt.ElideLeft)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.canal1 = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.canal1.sizePolicy().hasHeightForWidth())
        self.canal1.setSizePolicy(sizePolicy)
        self.canal1.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.canal1.setObjectName("canal1")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.canal1)
        self.verticalLayout_7.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_7.setSpacing(3)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.tabWidget.addTab(self.canal1, "")
        self.canal2 = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.canal2.sizePolicy().hasHeightForWidth())
        self.canal2.setSizePolicy(sizePolicy)
        self.canal2.setObjectName("canal2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.canal2)
        self.verticalLayout_6.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_6.setSpacing(3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.tabWidget.addTab(self.canal2, "")
        self.canal3 = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.canal3.sizePolicy().hasHeightForWidth())
        self.canal3.setSizePolicy(sizePolicy)
        self.canal3.setObjectName("canal3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.canal3)
        self.verticalLayout_4.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_4.setSpacing(3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tabWidget.addTab(self.canal3, "")
        self.canal4 = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.canal4.sizePolicy().hasHeightForWidth())
        self.canal4.setSizePolicy(sizePolicy)
        self.canal4.setObjectName("canal4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.canal4)
        self.verticalLayout_5.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_5.setSpacing(3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.tabWidget.addTab(self.canal4, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.controlFrame = QtWidgets.QFrame(self.frame1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.controlFrame.sizePolicy().hasHeightForWidth())
        self.controlFrame.setSizePolicy(sizePolicy)
        self.controlFrame.setMinimumSize(QtCore.QSize(0, 20))
        self.controlFrame.setAutoFillBackground(False)
        self.controlFrame.setStyleSheet("")
        self.controlFrame.setFrameShape(QtWidgets.QFrame.Box)
        self.controlFrame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.controlFrame.setObjectName("controlFrame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.controlFrame)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_2.addWidget(self.controlFrame)
        self.frame_5 = QtWidgets.QFrame(self.frame1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setMinimumSize(QtCore.QSize(10, 10))
        self.frame_5.setMaximumSize(QtCore.QSize(500, 500))
        self.frame_5.setBaseSize(QtCore.QSize(25, 25))
        self.frame_5.setAutoFillBackground(False)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.plotLayout2 = QtWidgets.QVBoxLayout(self.frame_5)
        self.plotLayout2.setContentsMargins(0, 0, 0, 0)
        self.plotLayout2.setSpacing(0)
        self.plotLayout2.setObjectName("plotLayout2")
        self.verticalLayout_2.addWidget(self.frame_5)
        self.horizontalLayout.addWidget(self.frame1)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_3.setSpacing(3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabSensors = QtWidgets.QTabWidget(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabSensors.sizePolicy().hasHeightForWidth())
        self.tabSensors.setSizePolicy(sizePolicy)
        self.tabSensors.setObjectName("tabSensors")
        self.imutab1 = QtWidgets.QWidget()
        self.imutab1.setObjectName("imutab1")
        self.IMU1Layout = QtWidgets.QVBoxLayout(self.imutab1)
        self.IMU1Layout.setContentsMargins(8, 3, 8, 3)
        self.IMU1Layout.setObjectName("IMU1Layout")
        self.tabSensors.addTab(self.imutab1, "")
        self.imutab2 = QtWidgets.QWidget()
        self.imutab2.setObjectName("imutab2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.imutab2)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.tabSensors.addTab(self.imutab2, "")
        self.imutab3 = QtWidgets.QWidget()
        self.imutab3.setObjectName("imutab3")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.imutab3)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.tabSensors.addTab(self.imutab3, "")
        self.adctab = QtWidgets.QWidget()
        self.adctab.setObjectName("adctab")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.adctab)
        self.verticalLayout_13.setContentsMargins(8, 3, 8, 3)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.tabSensors.addTab(self.adctab, "")
        self.verticalLayout_3.addWidget(self.tabSensors)
        self.plotCfgFrame = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotCfgFrame.sizePolicy().hasHeightForWidth())
        self.plotCfgFrame.setSizePolicy(sizePolicy)
        self.plotCfgFrame.setFrameShape(QtWidgets.QFrame.Box)
        self.plotCfgFrame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.plotCfgFrame.setObjectName("plotCfgFrame")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.plotCfgFrame)
        self.horizontalLayout_13.setContentsMargins(10, 3, 10, 4)
        self.horizontalLayout_13.setSpacing(5)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.verticalLayout_3.addWidget(self.plotCfgFrame)
        self.plotFrameOut = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotFrameOut.sizePolicy().hasHeightForWidth())
        self.plotFrameOut.setSizePolicy(sizePolicy)
        self.plotFrameOut.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.plotFrameOut.setFrameShadow(QtWidgets.QFrame.Raised)
        self.plotFrameOut.setObjectName("plotFrameOut")
        self.plotOutLayout = QtWidgets.QVBoxLayout(self.plotFrameOut)
        self.plotOutLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.plotOutLayout.setContentsMargins(0, 0, 0, 0)
        self.plotOutLayout.setSpacing(3)
        self.plotOutLayout.setObjectName("plotOutLayout")
        self.verticalLayout_3.addWidget(self.plotFrameOut)
        self.horizontalLayout.addWidget(self.frame_2)
        self.verticalLayout.addWidget(self.frame)
        self.bInit = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bInit.sizePolicy().hasHeightForWidth())
        self.bInit.setSizePolicy(sizePolicy)
        self.bInit.setObjectName("bInit")
        self.verticalLayout.addWidget(self.bInit)
        self.bLimpar = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bLimpar.sizePolicy().hasHeightForWidth())
        self.bLimpar.setSizePolicy(sizePolicy)
        self.bLimpar.setObjectName("bLimpar")
        self.verticalLayout.addWidget(self.bLimpar)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1090, 26))
        self.menubar.setObjectName("menubar")
        self.menuArquivo = QtWidgets.QMenu(self.menubar)
        self.menuArquivo.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.menuArquivo.setObjectName("menuArquivo")
        self.menuSelecionar_Porta = QtWidgets.QMenu(self.menuArquivo)
        self.menuSelecionar_Porta.setObjectName("menuSelecionar_Porta")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSalvar_dados = QtWidgets.QAction(MainWindow)
        self.actionSalvar_dados.setObjectName("actionSalvar_dados")
        self.actionSair = QtWidgets.QAction(MainWindow)
        self.actionSair.setObjectName("actionSair")
        self.actionCOM1 = QtWidgets.QAction(MainWindow)
        self.actionCOM1.setObjectName("actionCOM1")
        self.actionCOM2 = QtWidgets.QAction(MainWindow)
        self.actionCOM2.setObjectName("actionCOM2")
        self.actionCOM3 = QtWidgets.QAction(MainWindow)
        self.actionCOM3.setObjectName("actionCOM3")
        self.actionCOM4 = QtWidgets.QAction(MainWindow)
        self.actionCOM4.setObjectName("actionCOM4")
        self.actionCOM5 = QtWidgets.QAction(MainWindow)
        self.actionCOM5.setObjectName("actionCOM5")
        self.actionCOM6 = QtWidgets.QAction(MainWindow)
        self.actionCOM6.setObjectName("actionCOM6")
        self.actionCOM7 = QtWidgets.QAction(MainWindow)
        self.actionCOM7.setObjectName("actionCOM7")
        self.actionCOM8 = QtWidgets.QAction(MainWindow)
        self.actionCOM8.setObjectName("actionCOM8")
        self.actionCOM9 = QtWidgets.QAction(MainWindow)
        self.actionCOM9.setObjectName("actionCOM9")
        self.actionCOM10 = QtWidgets.QAction(MainWindow)
        self.actionCOM10.setObjectName("actionCOM10")
        self.actionCOM11 = QtWidgets.QAction(MainWindow)
        self.actionCOM11.setObjectName("actionCOM11")
        self.actionCOM12 = QtWidgets.QAction(MainWindow)
        self.actionCOM12.setObjectName("actionCOM12")
        self.actionUpload = QtWidgets.QAction(MainWindow)
        self.actionUpload.setObjectName("actionUpload")
        self.actionDefineWorkdir = QtWidgets.QAction(MainWindow)
        self.actionDefineWorkdir.setObjectName("actionDefineWorkdir")
        self.actionSavePlus = QtWidgets.QAction(MainWindow)
        self.actionSavePlus.setObjectName("actionSavePlus")
        self.actionWorkdirManager = QtWidgets.QAction(MainWindow)
        self.actionWorkdirManager.setObjectName("actionWorkdirManager")
        self.actionTeste = QtWidgets.QAction(MainWindow)
        self.actionTeste.setObjectName("actionTeste")
        self.menuSelecionar_Porta.addAction(self.actionCOM1)
        self.menuSelecionar_Porta.addAction(self.actionCOM2)
        self.menuSelecionar_Porta.addAction(self.actionCOM3)
        self.menuSelecionar_Porta.addAction(self.actionCOM4)
        self.menuSelecionar_Porta.addAction(self.actionCOM5)
        self.menuSelecionar_Porta.addAction(self.actionCOM6)
        self.menuSelecionar_Porta.addAction(self.actionCOM7)
        self.menuSelecionar_Porta.addAction(self.actionCOM8)
        self.menuSelecionar_Porta.addAction(self.actionCOM9)
        self.menuSelecionar_Porta.addAction(self.actionCOM10)
        self.menuSelecionar_Porta.addAction(self.actionCOM11)
        self.menuSelecionar_Porta.addAction(self.actionCOM12)
        self.menuArquivo.addAction(self.actionSalvar_dados)
        self.menuArquivo.addAction(self.actionUpload)
        self.menuArquivo.addAction(self.menuSelecionar_Porta.menuAction())
        self.menuArquivo.addSeparator()
        self.menuArquivo.addAction(self.actionSavePlus)
        self.menuArquivo.addAction(self.actionDefineWorkdir)
        self.menuArquivo.addAction(self.actionWorkdirManager)
        self.menuArquivo.addSeparator()
        self.menuArquivo.addAction(self.actionSair)
        self.menubar.addAction(self.menuArquivo.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabSensors.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ActVib"))
        self.label_4.setText(_translate("MainWindow", "Elapsed Time:"))
        self.elapsedTime.setText(_translate("MainWindow", " 0 s"))
        self.label_5.setText(_translate("MainWindow", "Time Delay:"))
        self.controlTime.setText(_translate("MainWindow", "0 s"))
        self.label_6.setText(_translate("MainWindow", "Sample Time:"))
        self.sampleTime.setText(_translate("MainWindow", "0 us"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.canal1), _translate("MainWindow", "Output 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.canal2), _translate("MainWindow", "Output 2"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.canal3), _translate("MainWindow", "Output 3"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.canal4), _translate("MainWindow", "Output 4"))
        self.tabSensors.setTabText(self.tabSensors.indexOf(self.imutab1), _translate("MainWindow", "IMU 1"))
        self.tabSensors.setTabText(self.tabSensors.indexOf(self.imutab2), _translate("MainWindow", "IMU 2"))
        self.tabSensors.setTabText(self.tabSensors.indexOf(self.imutab3), _translate("MainWindow", "IMU 3"))
        self.tabSensors.setTabText(self.tabSensors.indexOf(self.adctab), _translate("MainWindow", "ADC"))
        self.bInit.setText(_translate("MainWindow", "Start/Stop"))
        self.bLimpar.setText(_translate("MainWindow", "Reset Data"))
        self.menuArquivo.setTitle(_translate("MainWindow", "File"))
        self.menuSelecionar_Porta.setTitle(_translate("MainWindow", "Choose Port"))
        self.actionSalvar_dados.setText(_translate("MainWindow", "Save..."))
        self.actionSair.setText(_translate("MainWindow", "Quit"))
        self.actionCOM1.setText(_translate("MainWindow", "COM1"))
        self.actionCOM2.setText(_translate("MainWindow", "COM2"))
        self.actionCOM3.setText(_translate("MainWindow", "COM3"))
        self.actionCOM4.setText(_translate("MainWindow", "COM4"))
        self.actionCOM5.setText(_translate("MainWindow", "COM5"))
        self.actionCOM6.setText(_translate("MainWindow", "COM6"))
        self.actionCOM7.setText(_translate("MainWindow", "COM7"))
        self.actionCOM8.setText(_translate("MainWindow", "COM8"))
        self.actionCOM9.setText(_translate("MainWindow", "COM9"))
        self.actionCOM10.setText(_translate("MainWindow", "COM10"))
        self.actionCOM11.setText(_translate("MainWindow", "COM11"))
        self.actionCOM12.setText(_translate("MainWindow", "COM12"))
        self.actionUpload.setText(_translate("MainWindow", "Upload secondary and feedback responses..."))
        self.actionDefineWorkdir.setText(_translate("MainWindow", "Define Workdir"))
        self.actionSavePlus.setText(_translate("MainWindow", "Save and Update Metada in Workdir"))
        self.actionWorkdirManager.setText(_translate("MainWindow", "Workdir Manager"))
        self.actionTeste.setText(_translate("MainWindow", "Teste"))
