# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VibViewWindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(986, 765)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setLineWidth(0)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.label_4 = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.elapsedTime = QtWidgets.QLabel(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.elapsedTime.sizePolicy().hasHeightForWidth())
        self.elapsedTime.setSizePolicy(sizePolicy)
        self.elapsedTime.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.elapsedTime.setFont(font)
        self.elapsedTime.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.elapsedTime.setLineWidth(2)
        self.elapsedTime.setAlignment(QtCore.Qt.AlignCenter)
        self.elapsedTime.setObjectName("elapsedTime")
        self.horizontalLayout_3.addWidget(self.elapsedTime)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.label_5 = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.controlTime = QtWidgets.QLabel(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.controlTime.sizePolicy().hasHeightForWidth())
        self.controlTime.setSizePolicy(sizePolicy)
        self.controlTime.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.controlTime.setFont(font)
        self.controlTime.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.controlTime.setAlignment(QtCore.Qt.AlignCenter)
        self.controlTime.setObjectName("controlTime")
        self.horizontalLayout_3.addWidget(self.controlTime)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout.addWidget(self.frame_3)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setLineWidth(0)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(3, 0, 3, 0)
        self.horizontalLayout.setSpacing(4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame1 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame1.sizePolicy().hasHeightForWidth())
        self.frame1.setSizePolicy(sizePolicy)
        self.frame1.setObjectName("frame1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame1)
        self.verticalLayout_2.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_2.setSpacing(3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.frame1)
        self.tabWidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setBaseSize(QtCore.QSize(0, 0))
        self.tabWidget.setElideMode(QtCore.Qt.ElideLeft)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.canal1 = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.canal1.sizePolicy().hasHeightForWidth())
        self.canal1.setSizePolicy(sizePolicy)
        self.canal1.setObjectName("canal1")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.canal1)
        self.verticalLayout_7.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_7.setSpacing(3)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_4 = QtWidgets.QFrame(self.canal1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_4.setLineWidth(0)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_6.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_6.setSpacing(5)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.checkCanal1 = QtWidgets.QCheckBox(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkCanal1.sizePolicy().hasHeightForWidth())
        self.checkCanal1.setSizePolicy(sizePolicy)
        self.checkCanal1.setCheckable(True)
        self.checkCanal1.setChecked(True)
        self.checkCanal1.setObjectName("checkCanal1")
        self.horizontalLayout_6.addWidget(self.checkCanal1)
        self.comboCanal1 = QtWidgets.QComboBox(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboCanal1.sizePolicy().hasHeightForWidth())
        self.comboCanal1.setSizePolicy(sizePolicy)
        self.comboCanal1.setObjectName("comboCanal1")
        self.comboCanal1.addItem("")
        self.comboCanal1.addItem("")
        self.comboCanal1.addItem("")
        self.horizontalLayout_6.addWidget(self.comboCanal1)
        self.label_2 = QtWidgets.QLabel(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_6.addWidget(self.label_2)
        self.spinAmpl1 = QtWidgets.QDoubleSpinBox(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinAmpl1.sizePolicy().hasHeightForWidth())
        self.spinAmpl1.setSizePolicy(sizePolicy)
        self.spinAmpl1.setDecimals(3)
        self.spinAmpl1.setMaximum(1.0)
        self.spinAmpl1.setSingleStep(0.1)
        self.spinAmpl1.setProperty("value", 0.0)
        self.spinAmpl1.setObjectName("spinAmpl1")
        self.horizontalLayout_6.addWidget(self.spinAmpl1)
        self.label_3 = QtWidgets.QLabel(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_6.addWidget(self.label_3)
        self.spinFreq1 = QtWidgets.QDoubleSpinBox(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinFreq1.sizePolicy().hasHeightForWidth())
        self.spinFreq1.setSizePolicy(sizePolicy)
        self.spinFreq1.setMaximum(100.0)
        self.spinFreq1.setSingleStep(0.1)
        self.spinFreq1.setProperty("value", 10.0)
        self.spinFreq1.setObjectName("spinFreq1")
        self.horizontalLayout_6.addWidget(self.spinFreq1)
        self.verticalLayout_7.addWidget(self.frame_4)
        self.extrasCanal1 = QtWidgets.QFrame(self.canal1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.extrasCanal1.sizePolicy().hasHeightForWidth())
        self.extrasCanal1.setSizePolicy(sizePolicy)
        self.extrasCanal1.setMinimumSize(QtCore.QSize(0, 0))
        self.extrasCanal1.setAutoFillBackground(False)
        self.extrasCanal1.setStyleSheet("")
        self.extrasCanal1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.extrasCanal1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.extrasCanal1.setLineWidth(0)
        self.extrasCanal1.setObjectName("extrasCanal1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.extrasCanal1)
        self.horizontalLayout_2.setContentsMargins(2, 1, 0, 1)
        self.horizontalLayout_2.setSpacing(3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_26 = QtWidgets.QLabel(self.extrasCanal1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_26.sizePolicy().hasHeightForWidth())
        self.label_26.setSizePolicy(sizePolicy)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_2.addWidget(self.label_26)
        self.chirp1A2 = QtWidgets.QDoubleSpinBox(self.extrasCanal1)
        self.chirp1A2.setDecimals(3)
        self.chirp1A2.setMaximum(1.0)
        self.chirp1A2.setSingleStep(0.1)
        self.chirp1A2.setObjectName("chirp1A2")
        self.horizontalLayout_2.addWidget(self.chirp1A2)
        self.label_19 = QtWidgets.QLabel(self.extrasCanal1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_2.addWidget(self.label_19)
        self.chirp1Tinicio = QtWidgets.QSpinBox(self.extrasCanal1)
        self.chirp1Tinicio.setMaximum(255)
        self.chirp1Tinicio.setProperty("value", 10)
        self.chirp1Tinicio.setObjectName("chirp1Tinicio")
        self.horizontalLayout_2.addWidget(self.chirp1Tinicio)
        self.label_18 = QtWidgets.QLabel(self.extrasCanal1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_2.addWidget(self.label_18)
        self.chirp1DeltaI = QtWidgets.QDoubleSpinBox(self.extrasCanal1)
        self.chirp1DeltaI.setDecimals(1)
        self.chirp1DeltaI.setMinimum(0.1)
        self.chirp1DeltaI.setMaximum(25.5)
        self.chirp1DeltaI.setSingleStep(1.0)
        self.chirp1DeltaI.setProperty("value", 10.0)
        self.chirp1DeltaI.setObjectName("chirp1DeltaI")
        self.horizontalLayout_2.addWidget(self.chirp1DeltaI)
        self.label_20 = QtWidgets.QLabel(self.extrasCanal1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_2.addWidget(self.label_20)
        self.chirp1Tfim = QtWidgets.QSpinBox(self.extrasCanal1)
        self.chirp1Tfim.setMaximum(255)
        self.chirp1Tfim.setProperty("value", 100)
        self.chirp1Tfim.setObjectName("chirp1Tfim")
        self.horizontalLayout_2.addWidget(self.chirp1Tfim)
        self.label_25 = QtWidgets.QLabel(self.extrasCanal1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_25.sizePolicy().hasHeightForWidth())
        self.label_25.setSizePolicy(sizePolicy)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_2.addWidget(self.label_25)
        self.chirp1DeltaF = QtWidgets.QDoubleSpinBox(self.extrasCanal1)
        self.chirp1DeltaF.setDecimals(1)
        self.chirp1DeltaF.setMinimum(0.1)
        self.chirp1DeltaF.setMaximum(25.5)
        self.chirp1DeltaF.setProperty("value", 10.0)
        self.chirp1DeltaF.setObjectName("chirp1DeltaF")
        self.horizontalLayout_2.addWidget(self.chirp1DeltaF)
        self.verticalLayout_7.addWidget(self.extrasCanal1)
        self.tabWidget.addTab(self.canal1, "")
        self.canal2 = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.canal2.sizePolicy().hasHeightForWidth())
        self.canal2.setSizePolicy(sizePolicy)
        self.canal2.setObjectName("canal2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.canal2)
        self.verticalLayout_6.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_6.setSpacing(3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_10 = QtWidgets.QFrame(self.canal2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_10.sizePolicy().hasHeightForWidth())
        self.frame_10.setSizePolicy(sizePolicy)
        self.frame_10.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_10.setLineWidth(0)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_11.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_11.setSpacing(5)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.checkCanal2 = QtWidgets.QCheckBox(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkCanal2.sizePolicy().hasHeightForWidth())
        self.checkCanal2.setSizePolicy(sizePolicy)
        self.checkCanal2.setCheckable(True)
        self.checkCanal2.setChecked(True)
        self.checkCanal2.setObjectName("checkCanal2")
        self.horizontalLayout_11.addWidget(self.checkCanal2)
        self.comboCanal2 = QtWidgets.QComboBox(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboCanal2.sizePolicy().hasHeightForWidth())
        self.comboCanal2.setSizePolicy(sizePolicy)
        self.comboCanal2.setObjectName("comboCanal2")
        self.comboCanal2.addItem("")
        self.comboCanal2.addItem("")
        self.comboCanal2.addItem("")
        self.horizontalLayout_11.addWidget(self.comboCanal2)
        self.label_6 = QtWidgets.QLabel(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_11.addWidget(self.label_6)
        self.spinAmpl2 = QtWidgets.QDoubleSpinBox(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinAmpl2.sizePolicy().hasHeightForWidth())
        self.spinAmpl2.setSizePolicy(sizePolicy)
        self.spinAmpl2.setDecimals(3)
        self.spinAmpl2.setMaximum(1.0)
        self.spinAmpl2.setSingleStep(0.1)
        self.spinAmpl2.setProperty("value", 0.0)
        self.spinAmpl2.setObjectName("spinAmpl2")
        self.horizontalLayout_11.addWidget(self.spinAmpl2)
        self.label_7 = QtWidgets.QLabel(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_11.addWidget(self.label_7)
        self.spinFreq2 = QtWidgets.QDoubleSpinBox(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinFreq2.sizePolicy().hasHeightForWidth())
        self.spinFreq2.setSizePolicy(sizePolicy)
        self.spinFreq2.setMaximum(100.0)
        self.spinFreq2.setSingleStep(0.1)
        self.spinFreq2.setProperty("value", 10.0)
        self.spinFreq2.setObjectName("spinFreq2")
        self.horizontalLayout_11.addWidget(self.spinFreq2)
        self.verticalLayout_6.addWidget(self.frame_10)
        self.extrasCanal2 = QtWidgets.QFrame(self.canal2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.extrasCanal2.sizePolicy().hasHeightForWidth())
        self.extrasCanal2.setSizePolicy(sizePolicy)
        self.extrasCanal2.setMinimumSize(QtCore.QSize(0, 0))
        self.extrasCanal2.setAutoFillBackground(False)
        self.extrasCanal2.setStyleSheet("")
        self.extrasCanal2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.extrasCanal2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.extrasCanal2.setLineWidth(0)
        self.extrasCanal2.setObjectName("extrasCanal2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.extrasCanal2)
        self.horizontalLayout_4.setContentsMargins(2, 1, 0, 1)
        self.horizontalLayout_4.setSpacing(3)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_27 = QtWidgets.QLabel(self.extrasCanal2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_27.sizePolicy().hasHeightForWidth())
        self.label_27.setSizePolicy(sizePolicy)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_4.addWidget(self.label_27)
        self.chirp2A2 = QtWidgets.QDoubleSpinBox(self.extrasCanal2)
        self.chirp2A2.setDecimals(3)
        self.chirp2A2.setMaximum(1.0)
        self.chirp2A2.setSingleStep(0.1)
        self.chirp2A2.setObjectName("chirp2A2")
        self.horizontalLayout_4.addWidget(self.chirp2A2)
        self.label_21 = QtWidgets.QLabel(self.extrasCanal2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_21.sizePolicy().hasHeightForWidth())
        self.label_21.setSizePolicy(sizePolicy)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_4.addWidget(self.label_21)
        self.chirp2Tinicio = QtWidgets.QSpinBox(self.extrasCanal2)
        self.chirp2Tinicio.setMaximum(255)
        self.chirp2Tinicio.setProperty("value", 10)
        self.chirp2Tinicio.setObjectName("chirp2Tinicio")
        self.horizontalLayout_4.addWidget(self.chirp2Tinicio)
        self.label_22 = QtWidgets.QLabel(self.extrasCanal2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_22.sizePolicy().hasHeightForWidth())
        self.label_22.setSizePolicy(sizePolicy)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_4.addWidget(self.label_22)
        self.chirp2DeltaI = QtWidgets.QDoubleSpinBox(self.extrasCanal2)
        self.chirp2DeltaI.setDecimals(1)
        self.chirp2DeltaI.setMinimum(0.1)
        self.chirp2DeltaI.setMaximum(25.5)
        self.chirp2DeltaI.setSingleStep(1.0)
        self.chirp2DeltaI.setProperty("value", 10.0)
        self.chirp2DeltaI.setObjectName("chirp2DeltaI")
        self.horizontalLayout_4.addWidget(self.chirp2DeltaI)
        self.label_23 = QtWidgets.QLabel(self.extrasCanal2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_23.sizePolicy().hasHeightForWidth())
        self.label_23.setSizePolicy(sizePolicy)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_4.addWidget(self.label_23)
        self.chirp2Tfim = QtWidgets.QSpinBox(self.extrasCanal2)
        self.chirp2Tfim.setMaximum(255)
        self.chirp2Tfim.setProperty("value", 100)
        self.chirp2Tfim.setObjectName("chirp2Tfim")
        self.horizontalLayout_4.addWidget(self.chirp2Tfim)
        self.label_47 = QtWidgets.QLabel(self.extrasCanal2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_47.sizePolicy().hasHeightForWidth())
        self.label_47.setSizePolicy(sizePolicy)
        self.label_47.setObjectName("label_47")
        self.horizontalLayout_4.addWidget(self.label_47)
        self.chirp2DeltaF = QtWidgets.QDoubleSpinBox(self.extrasCanal2)
        self.chirp2DeltaF.setDecimals(1)
        self.chirp2DeltaF.setMinimum(0.1)
        self.chirp2DeltaF.setMaximum(25.5)
        self.chirp2DeltaF.setProperty("value", 10.0)
        self.chirp2DeltaF.setObjectName("chirp2DeltaF")
        self.horizontalLayout_4.addWidget(self.chirp2DeltaF)
        self.verticalLayout_6.addWidget(self.extrasCanal2)
        self.tabWidget.addTab(self.canal2, "")
        self.canal3 = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.canal3.sizePolicy().hasHeightForWidth())
        self.canal3.setSizePolicy(sizePolicy)
        self.canal3.setObjectName("canal3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.canal3)
        self.verticalLayout_4.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_4.setSpacing(3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_8 = QtWidgets.QFrame(self.canal3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_8.sizePolicy().hasHeightForWidth())
        self.frame_8.setSizePolicy(sizePolicy)
        self.frame_8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_8.setLineWidth(0)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_7.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_7.setSpacing(5)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.checkCanal3 = QtWidgets.QCheckBox(self.frame_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkCanal3.sizePolicy().hasHeightForWidth())
        self.checkCanal3.setSizePolicy(sizePolicy)
        self.checkCanal3.setCheckable(True)
        self.checkCanal3.setChecked(True)
        self.checkCanal3.setObjectName("checkCanal3")
        self.horizontalLayout_7.addWidget(self.checkCanal3)
        self.comboCanal3 = QtWidgets.QComboBox(self.frame_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboCanal3.sizePolicy().hasHeightForWidth())
        self.comboCanal3.setSizePolicy(sizePolicy)
        self.comboCanal3.setObjectName("comboCanal3")
        self.comboCanal3.addItem("")
        self.comboCanal3.addItem("")
        self.comboCanal3.addItem("")
        self.horizontalLayout_7.addWidget(self.comboCanal3)
        self.label_28 = QtWidgets.QLabel(self.frame_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_28.sizePolicy().hasHeightForWidth())
        self.label_28.setSizePolicy(sizePolicy)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_7.addWidget(self.label_28)
        self.spinAmpl3 = QtWidgets.QDoubleSpinBox(self.frame_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinAmpl3.sizePolicy().hasHeightForWidth())
        self.spinAmpl3.setSizePolicy(sizePolicy)
        self.spinAmpl3.setDecimals(3)
        self.spinAmpl3.setMaximum(1.0)
        self.spinAmpl3.setSingleStep(0.1)
        self.spinAmpl3.setProperty("value", 0.0)
        self.spinAmpl3.setObjectName("spinAmpl3")
        self.horizontalLayout_7.addWidget(self.spinAmpl3)
        self.label_29 = QtWidgets.QLabel(self.frame_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_29.sizePolicy().hasHeightForWidth())
        self.label_29.setSizePolicy(sizePolicy)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_7.addWidget(self.label_29)
        self.spinFreq3 = QtWidgets.QDoubleSpinBox(self.frame_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinFreq3.sizePolicy().hasHeightForWidth())
        self.spinFreq3.setSizePolicy(sizePolicy)
        self.spinFreq3.setMaximum(100.0)
        self.spinFreq3.setSingleStep(0.1)
        self.spinFreq3.setProperty("value", 10.0)
        self.spinFreq3.setObjectName("spinFreq3")
        self.horizontalLayout_7.addWidget(self.spinFreq3)
        self.verticalLayout_4.addWidget(self.frame_8)
        self.extrasCanal3 = QtWidgets.QFrame(self.canal3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.extrasCanal3.sizePolicy().hasHeightForWidth())
        self.extrasCanal3.setSizePolicy(sizePolicy)
        self.extrasCanal3.setMinimumSize(QtCore.QSize(0, 0))
        self.extrasCanal3.setAutoFillBackground(False)
        self.extrasCanal3.setStyleSheet("")
        self.extrasCanal3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.extrasCanal3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.extrasCanal3.setLineWidth(0)
        self.extrasCanal3.setObjectName("extrasCanal3")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.extrasCanal3)
        self.horizontalLayout_8.setContentsMargins(2, 1, 0, 1)
        self.horizontalLayout_8.setSpacing(3)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_35 = QtWidgets.QLabel(self.extrasCanal3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_35.sizePolicy().hasHeightForWidth())
        self.label_35.setSizePolicy(sizePolicy)
        self.label_35.setObjectName("label_35")
        self.horizontalLayout_8.addWidget(self.label_35)
        self.chirp3A2 = QtWidgets.QDoubleSpinBox(self.extrasCanal3)
        self.chirp3A2.setDecimals(3)
        self.chirp3A2.setMaximum(1.0)
        self.chirp3A2.setSingleStep(0.1)
        self.chirp3A2.setObjectName("chirp3A2")
        self.horizontalLayout_8.addWidget(self.chirp3A2)
        self.label_36 = QtWidgets.QLabel(self.extrasCanal3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_36.sizePolicy().hasHeightForWidth())
        self.label_36.setSizePolicy(sizePolicy)
        self.label_36.setObjectName("label_36")
        self.horizontalLayout_8.addWidget(self.label_36)
        self.chirp3Tinicio = QtWidgets.QSpinBox(self.extrasCanal3)
        self.chirp3Tinicio.setMaximum(255)
        self.chirp3Tinicio.setProperty("value", 10)
        self.chirp3Tinicio.setObjectName("chirp3Tinicio")
        self.horizontalLayout_8.addWidget(self.chirp3Tinicio)
        self.label_37 = QtWidgets.QLabel(self.extrasCanal3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_37.sizePolicy().hasHeightForWidth())
        self.label_37.setSizePolicy(sizePolicy)
        self.label_37.setObjectName("label_37")
        self.horizontalLayout_8.addWidget(self.label_37)
        self.chirp3DeltaI = QtWidgets.QDoubleSpinBox(self.extrasCanal3)
        self.chirp3DeltaI.setDecimals(1)
        self.chirp3DeltaI.setMinimum(0.1)
        self.chirp3DeltaI.setMaximum(25.5)
        self.chirp3DeltaI.setSingleStep(1.0)
        self.chirp3DeltaI.setProperty("value", 10.0)
        self.chirp3DeltaI.setObjectName("chirp3DeltaI")
        self.horizontalLayout_8.addWidget(self.chirp3DeltaI)
        self.label_38 = QtWidgets.QLabel(self.extrasCanal3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_38.sizePolicy().hasHeightForWidth())
        self.label_38.setSizePolicy(sizePolicy)
        self.label_38.setObjectName("label_38")
        self.horizontalLayout_8.addWidget(self.label_38)
        self.chirp3Tfim = QtWidgets.QSpinBox(self.extrasCanal3)
        self.chirp3Tfim.setMaximum(255)
        self.chirp3Tfim.setProperty("value", 100)
        self.chirp3Tfim.setObjectName("chirp3Tfim")
        self.horizontalLayout_8.addWidget(self.chirp3Tfim)
        self.label_39 = QtWidgets.QLabel(self.extrasCanal3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_39.sizePolicy().hasHeightForWidth())
        self.label_39.setSizePolicy(sizePolicy)
        self.label_39.setObjectName("label_39")
        self.horizontalLayout_8.addWidget(self.label_39)
        self.chirp3DeltaF = QtWidgets.QDoubleSpinBox(self.extrasCanal3)
        self.chirp3DeltaF.setDecimals(1)
        self.chirp3DeltaF.setMinimum(0.1)
        self.chirp3DeltaF.setMaximum(25.5)
        self.chirp3DeltaF.setProperty("value", 10.0)
        self.chirp3DeltaF.setObjectName("chirp3DeltaF")
        self.horizontalLayout_8.addWidget(self.chirp3DeltaF)
        self.verticalLayout_4.addWidget(self.extrasCanal3)
        self.tabWidget.addTab(self.canal3, "")
        self.canal4 = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.canal4.sizePolicy().hasHeightForWidth())
        self.canal4.setSizePolicy(sizePolicy)
        self.canal4.setObjectName("canal4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.canal4)
        self.verticalLayout_5.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_5.setSpacing(3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_9 = QtWidgets.QFrame(self.canal4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_9.sizePolicy().hasHeightForWidth())
        self.frame_9.setSizePolicy(sizePolicy)
        self.frame_9.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_9.setLineWidth(0)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_9.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_9.setSpacing(5)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.checkCanal4 = QtWidgets.QCheckBox(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkCanal4.sizePolicy().hasHeightForWidth())
        self.checkCanal4.setSizePolicy(sizePolicy)
        self.checkCanal4.setCheckable(True)
        self.checkCanal4.setChecked(True)
        self.checkCanal4.setObjectName("checkCanal4")
        self.horizontalLayout_9.addWidget(self.checkCanal4)
        self.comboCanal4 = QtWidgets.QComboBox(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboCanal4.sizePolicy().hasHeightForWidth())
        self.comboCanal4.setSizePolicy(sizePolicy)
        self.comboCanal4.setObjectName("comboCanal4")
        self.comboCanal4.addItem("")
        self.comboCanal4.addItem("")
        self.comboCanal4.addItem("")
        self.horizontalLayout_9.addWidget(self.comboCanal4)
        self.label_40 = QtWidgets.QLabel(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_40.sizePolicy().hasHeightForWidth())
        self.label_40.setSizePolicy(sizePolicy)
        self.label_40.setObjectName("label_40")
        self.horizontalLayout_9.addWidget(self.label_40)
        self.spinAmpl4 = QtWidgets.QDoubleSpinBox(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinAmpl4.sizePolicy().hasHeightForWidth())
        self.spinAmpl4.setSizePolicy(sizePolicy)
        self.spinAmpl4.setDecimals(3)
        self.spinAmpl4.setMaximum(1.0)
        self.spinAmpl4.setSingleStep(0.1)
        self.spinAmpl4.setProperty("value", 0.0)
        self.spinAmpl4.setObjectName("spinAmpl4")
        self.horizontalLayout_9.addWidget(self.spinAmpl4)
        self.label_41 = QtWidgets.QLabel(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_41.sizePolicy().hasHeightForWidth())
        self.label_41.setSizePolicy(sizePolicy)
        self.label_41.setObjectName("label_41")
        self.horizontalLayout_9.addWidget(self.label_41)
        self.spinFreq4 = QtWidgets.QDoubleSpinBox(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinFreq4.sizePolicy().hasHeightForWidth())
        self.spinFreq4.setSizePolicy(sizePolicy)
        self.spinFreq4.setMaximum(100.0)
        self.spinFreq4.setSingleStep(0.1)
        self.spinFreq4.setProperty("value", 10.0)
        self.spinFreq4.setObjectName("spinFreq4")
        self.horizontalLayout_9.addWidget(self.spinFreq4)
        self.verticalLayout_5.addWidget(self.frame_9)
        self.extrasCanal4 = QtWidgets.QFrame(self.canal4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.extrasCanal4.sizePolicy().hasHeightForWidth())
        self.extrasCanal4.setSizePolicy(sizePolicy)
        self.extrasCanal4.setMinimumSize(QtCore.QSize(0, 0))
        self.extrasCanal4.setAutoFillBackground(False)
        self.extrasCanal4.setStyleSheet("")
        self.extrasCanal4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.extrasCanal4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.extrasCanal4.setLineWidth(0)
        self.extrasCanal4.setObjectName("extrasCanal4")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.extrasCanal4)
        self.horizontalLayout_10.setContentsMargins(2, 1, 0, 1)
        self.horizontalLayout_10.setSpacing(3)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_42 = QtWidgets.QLabel(self.extrasCanal4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_42.sizePolicy().hasHeightForWidth())
        self.label_42.setSizePolicy(sizePolicy)
        self.label_42.setObjectName("label_42")
        self.horizontalLayout_10.addWidget(self.label_42)
        self.chirp4A2 = QtWidgets.QDoubleSpinBox(self.extrasCanal4)
        self.chirp4A2.setDecimals(3)
        self.chirp4A2.setMaximum(1.0)
        self.chirp4A2.setSingleStep(0.1)
        self.chirp4A2.setObjectName("chirp4A2")
        self.horizontalLayout_10.addWidget(self.chirp4A2)
        self.label_43 = QtWidgets.QLabel(self.extrasCanal4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_43.sizePolicy().hasHeightForWidth())
        self.label_43.setSizePolicy(sizePolicy)
        self.label_43.setObjectName("label_43")
        self.horizontalLayout_10.addWidget(self.label_43)
        self.chirp4Tinicio = QtWidgets.QSpinBox(self.extrasCanal4)
        self.chirp4Tinicio.setMaximum(255)
        self.chirp4Tinicio.setProperty("value", 10)
        self.chirp4Tinicio.setObjectName("chirp4Tinicio")
        self.horizontalLayout_10.addWidget(self.chirp4Tinicio)
        self.label_44 = QtWidgets.QLabel(self.extrasCanal4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_44.sizePolicy().hasHeightForWidth())
        self.label_44.setSizePolicy(sizePolicy)
        self.label_44.setObjectName("label_44")
        self.horizontalLayout_10.addWidget(self.label_44)
        self.chirp4DeltaI = QtWidgets.QDoubleSpinBox(self.extrasCanal4)
        self.chirp4DeltaI.setDecimals(1)
        self.chirp4DeltaI.setMinimum(0.1)
        self.chirp4DeltaI.setMaximum(25.5)
        self.chirp4DeltaI.setSingleStep(1.0)
        self.chirp4DeltaI.setProperty("value", 10.0)
        self.chirp4DeltaI.setObjectName("chirp4DeltaI")
        self.horizontalLayout_10.addWidget(self.chirp4DeltaI)
        self.label_45 = QtWidgets.QLabel(self.extrasCanal4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_45.sizePolicy().hasHeightForWidth())
        self.label_45.setSizePolicy(sizePolicy)
        self.label_45.setObjectName("label_45")
        self.horizontalLayout_10.addWidget(self.label_45)
        self.chirp4Tfim = QtWidgets.QSpinBox(self.extrasCanal4)
        self.chirp4Tfim.setMaximum(255)
        self.chirp4Tfim.setProperty("value", 100)
        self.chirp4Tfim.setObjectName("chirp4Tfim")
        self.horizontalLayout_10.addWidget(self.chirp4Tfim)
        self.label_46 = QtWidgets.QLabel(self.extrasCanal4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_46.sizePolicy().hasHeightForWidth())
        self.label_46.setSizePolicy(sizePolicy)
        self.label_46.setObjectName("label_46")
        self.horizontalLayout_10.addWidget(self.label_46)
        self.chirp4DeltaF = QtWidgets.QDoubleSpinBox(self.extrasCanal4)
        self.chirp4DeltaF.setDecimals(1)
        self.chirp4DeltaF.setMinimum(0.1)
        self.chirp4DeltaF.setMaximum(25.5)
        self.chirp4DeltaF.setProperty("value", 10.0)
        self.chirp4DeltaF.setObjectName("chirp4DeltaF")
        self.horizontalLayout_10.addWidget(self.chirp4DeltaF)
        self.verticalLayout_5.addWidget(self.extrasCanal4)
        self.tabWidget.addTab(self.canal4, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.comboCanaisControle = QtWidgets.QComboBox(self.frame1)
        self.comboCanaisControle.setObjectName("comboCanaisControle")
        self.comboCanaisControle.addItem("")
        self.comboCanaisControle.addItem("")
        self.verticalLayout_2.addWidget(self.comboCanaisControle)
        self.Controle = QtWidgets.QFrame(self.frame1)
        self.Controle.setAutoFillBackground(False)
        self.Controle.setStyleSheet("")
        self.Controle.setFrameShape(QtWidgets.QFrame.Box)
        self.Controle.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Controle.setObjectName("Controle")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.Controle)
        self.horizontalLayout_5.setContentsMargins(5, 5, 0, 5)
        self.horizontalLayout_5.setSpacing(3)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.checkControle = QtWidgets.QCheckBox(self.Controle)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkControle.sizePolicy().hasHeightForWidth())
        self.checkControle.setSizePolicy(sizePolicy)
        self.checkControle.setObjectName("checkControle")
        self.horizontalLayout_5.addWidget(self.checkControle)
        self.line_4 = QtWidgets.QFrame(self.Controle)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout_5.addWidget(self.line_4)
        self.frame_7 = QtWidgets.QFrame(self.Controle)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_7.sizePolicy().hasHeightForWidth())
        self.frame_7.setSizePolicy(sizePolicy)
        self.frame_7.setMinimumSize(QtCore.QSize(0, 150))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_7)
        self.gridLayout_2.setContentsMargins(-1, 3, -1, 3)
        self.gridLayout_2.setVerticalSpacing(3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.comboCanalPerturb = QtWidgets.QComboBox(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboCanalPerturb.sizePolicy().hasHeightForWidth())
        self.comboCanalPerturb.setSizePolicy(sizePolicy)
        self.comboCanalPerturb.setObjectName("comboCanalPerturb")
        self.comboCanalPerturb.addItem("")
        self.comboCanalPerturb.addItem("")
        self.comboCanalPerturb.addItem("")
        self.comboCanalPerturb.addItem("")
        self.gridLayout_2.addWidget(self.comboCanalPerturb, 0, 4, 1, 5)
        self.label_24 = QtWidgets.QLabel(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_24.sizePolicy().hasHeightForWidth())
        self.label_24.setSizePolicy(sizePolicy)
        self.label_24.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_24.setObjectName("label_24")
        self.gridLayout_2.addWidget(self.label_24, 0, 3, 1, 1)
        self.label_48 = QtWidgets.QLabel(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_48.sizePolicy().hasHeightForWidth())
        self.label_48.setSizePolicy(sizePolicy)
        self.label_48.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_48.setObjectName("label_48")
        self.gridLayout_2.addWidget(self.label_48, 1, 3, 1, 1)
        self.comboRef = QtWidgets.QComboBox(self.frame_7)
        self.comboRef.setObjectName("comboRef")
        self.comboRef.addItem("")
        self.comboRef.addItem("")
        self.comboRef.addItem("")
        self.comboRef.addItem("")
        self.comboRef.addItem("")
        self.comboRef.addItem("")
        self.comboRef.addItem("")
        self.comboRef.addItem("")
        self.comboRef.addItem("")
        self.comboRef.addItem("")
        self.comboRef.addItem("")
        self.comboRef.addItem("")
        self.gridLayout_2.addWidget(self.comboRef, 2, 4, 1, 5)
        self.label_8 = QtWidgets.QLabel(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 4, 3, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.frame_7)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_2.addWidget(self.line_3, 5, 4, 3, 1)
        self.label_16 = QtWidgets.QLabel(self.frame_7)
        self.label_16.setObjectName("label_16")
        self.gridLayout_2.addWidget(self.label_16, 2, 3, 1, 1)
        self.comboErro = QtWidgets.QComboBox(self.frame_7)
        self.comboErro.setObjectName("comboErro")
        self.comboErro.addItem("")
        self.comboErro.addItem("")
        self.comboErro.addItem("")
        self.comboErro.addItem("")
        self.comboErro.addItem("")
        self.comboErro.addItem("")
        self.comboErro.addItem("")
        self.comboErro.addItem("")
        self.comboErro.addItem("")
        self.comboErro.addItem("")
        self.comboErro.addItem("")
        self.comboErro.addItem("")
        self.gridLayout_2.addWidget(self.comboErro, 3, 4, 1, 5)
        self.comboAlgoritmo = QtWidgets.QComboBox(self.frame_7)
        self.comboAlgoritmo.setObjectName("comboAlgoritmo")
        self.comboAlgoritmo.addItem("")
        self.comboAlgoritmo.addItem("")
        self.comboAlgoritmo.addItem("")
        self.gridLayout_2.addWidget(self.comboAlgoritmo, 4, 8, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.frame_7)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 6, 3, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.frame_7)
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 3, 3, 1, 1)
        self.comboCanalControle = QtWidgets.QComboBox(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboCanalControle.sizePolicy().hasHeightForWidth())
        self.comboCanalControle.setSizePolicy(sizePolicy)
        self.comboCanalControle.setObjectName("comboCanalControle")
        self.comboCanalControle.addItem("")
        self.comboCanalControle.addItem("")
        self.comboCanalControle.addItem("")
        self.comboCanalControle.addItem("")
        self.gridLayout_2.addWidget(self.comboCanalControle, 1, 4, 1, 5)
        self.normCtrl = QtWidgets.QLineEdit(self.frame_7)
        self.normCtrl.setObjectName("normCtrl")
        self.gridLayout_2.addWidget(self.normCtrl, 7, 8, 1, 1)
        self.passoCtrl = QtWidgets.QLineEdit(self.frame_7)
        self.passoCtrl.setObjectName("passoCtrl")
        self.gridLayout_2.addWidget(self.passoCtrl, 6, 8, 1, 1)
        self.spinMemCtrl = QtWidgets.QSpinBox(self.frame_7)
        self.spinMemCtrl.setMinimum(1)
        self.spinMemCtrl.setMaximum(3000)
        self.spinMemCtrl.setProperty("value", 100)
        self.spinMemCtrl.setObjectName("spinMemCtrl")
        self.gridLayout_2.addWidget(self.spinMemCtrl, 5, 8, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.frame_7)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 5, 5, 1, 3)
        self.label_11 = QtWidgets.QLabel(self.frame_7)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 7, 5, 1, 3)
        self.label_9 = QtWidgets.QLabel(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 6, 5, 1, 3)
        self.checkAlgOn = QtWidgets.QCheckBox(self.frame_7)
        self.checkAlgOn.setObjectName("checkAlgOn")
        self.gridLayout_2.addWidget(self.checkAlgOn, 4, 4, 1, 2)
        self.spinTAlgOn = QtWidgets.QSpinBox(self.frame_7)
        self.spinTAlgOn.setObjectName("spinTAlgOn")
        self.gridLayout_2.addWidget(self.spinTAlgOn, 4, 6, 1, 2)
        self.horizontalLayout_5.addWidget(self.frame_7)
        self.verticalLayout_2.addWidget(self.Controle)
        self.frame_5 = QtWidgets.QFrame(self.frame1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setMinimumSize(QtCore.QSize(10, 10))
        self.frame_5.setMaximumSize(QtCore.QSize(500, 500))
        self.frame_5.setBaseSize(QtCore.QSize(25, 25))
        self.frame_5.setAutoFillBackground(False)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.plotLayout2 = QtWidgets.QVBoxLayout(self.frame_5)
        self.plotLayout2.setContentsMargins(0, 0, 0, 0)
        self.plotLayout2.setSpacing(0)
        self.plotLayout2.setObjectName("plotLayout2")
        self.verticalLayout_2.addWidget(self.frame_5)
        self.horizontalLayout.addWidget(self.frame1)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_3.setSpacing(3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabSensors = QtWidgets.QTabWidget(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabSensors.sizePolicy().hasHeightForWidth())
        self.tabSensors.setSizePolicy(sizePolicy)
        self.tabSensors.setObjectName("tabSensors")
        self.imutab = QtWidgets.QWidget()
        self.imutab.setObjectName("imutab")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.imutab)
        self.verticalLayout_12.setContentsMargins(8, 3, 8, 3)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.imuframe = QtWidgets.QFrame(self.imutab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imuframe.sizePolicy().hasHeightForWidth())
        self.imuframe.setSizePolicy(sizePolicy)
        self.imuframe.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.imuframe.setFrameShadow(QtWidgets.QFrame.Plain)
        self.imuframe.setLineWidth(0)
        self.imuframe.setObjectName("imuframe")
        self.gridLayout = QtWidgets.QGridLayout(self.imuframe)
        self.gridLayout.setContentsMargins(3, 2, 3, 2)
        self.gridLayout.setHorizontalSpacing(6)
        self.gridLayout.setVerticalSpacing(1)
        self.gridLayout.setObjectName("gridLayout")
        self.checkAccX = QtWidgets.QCheckBox(self.imuframe)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkAccX.sizePolicy().hasHeightForWidth())
        self.checkAccX.setSizePolicy(sizePolicy)
        self.checkAccX.setChecked(True)
        self.checkAccX.setObjectName("checkAccX")
        self.gridLayout.addWidget(self.checkAccX, 1, 3, 1, 1)
        self.checkGyroX = QtWidgets.QCheckBox(self.imuframe)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkGyroX.sizePolicy().hasHeightForWidth())
        self.checkGyroX.setSizePolicy(sizePolicy)
        self.checkGyroX.setChecked(True)
        self.checkGyroX.setObjectName("checkGyroX")
        self.gridLayout.addWidget(self.checkGyroX, 1, 4, 1, 1)
        self.checkGyroZ = QtWidgets.QCheckBox(self.imuframe)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkGyroZ.sizePolicy().hasHeightForWidth())
        self.checkGyroZ.setSizePolicy(sizePolicy)
        self.checkGyroZ.setChecked(True)
        self.checkGyroZ.setObjectName("checkGyroZ")
        self.gridLayout.addWidget(self.checkGyroZ, 3, 4, 1, 1)
        self.checkAccY = QtWidgets.QCheckBox(self.imuframe)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkAccY.sizePolicy().hasHeightForWidth())
        self.checkAccY.setSizePolicy(sizePolicy)
        self.checkAccY.setChecked(True)
        self.checkAccY.setObjectName("checkAccY")
        self.gridLayout.addWidget(self.checkAccY, 2, 3, 1, 1)
        self.checkGyroY = QtWidgets.QCheckBox(self.imuframe)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkGyroY.sizePolicy().hasHeightForWidth())
        self.checkGyroY.setSizePolicy(sizePolicy)
        self.checkGyroY.setChecked(True)
        self.checkGyroY.setObjectName("checkGyroY")
        self.gridLayout.addWidget(self.checkGyroY, 2, 4, 1, 1)
        self.checkAccZ = QtWidgets.QCheckBox(self.imuframe)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkAccZ.sizePolicy().hasHeightForWidth())
        self.checkAccZ.setSizePolicy(sizePolicy)
        self.checkAccZ.setChecked(True)
        self.checkAccZ.setObjectName("checkAccZ")
        self.gridLayout.addWidget(self.checkAccZ, 3, 3, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.imuframe)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 1, 6, 1, 1)
        self.comboGyroRange = QtWidgets.QComboBox(self.imuframe)
        self.comboGyroRange.setObjectName("comboGyroRange")
        self.comboGyroRange.addItem("")
        self.comboGyroRange.addItem("")
        self.comboGyroRange.addItem("")
        self.comboGyroRange.addItem("")
        self.gridLayout.addWidget(self.comboGyroRange, 2, 7, 1, 1)
        self.comboAccRange = QtWidgets.QComboBox(self.imuframe)
        self.comboAccRange.setObjectName("comboAccRange")
        self.comboAccRange.addItem("")
        self.comboAccRange.addItem("")
        self.comboAccRange.addItem("")
        self.comboAccRange.addItem("")
        self.gridLayout.addWidget(self.comboAccRange, 1, 7, 1, 1)
        self.comboFilter = QtWidgets.QComboBox(self.imuframe)
        self.comboFilter.setObjectName("comboFilter")
        self.comboFilter.addItem("")
        self.comboFilter.addItem("")
        self.comboFilter.addItem("")
        self.comboFilter.addItem("")
        self.comboFilter.addItem("")
        self.comboFilter.addItem("")
        self.comboFilter.addItem("")
        self.gridLayout.addWidget(self.comboFilter, 3, 7, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.imuframe)
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 3, 6, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.imuframe)
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 2, 6, 1, 1)
        self.line = QtWidgets.QFrame(self.imuframe)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 1, 5, 3, 1)
        self.label = QtWidgets.QLabel(self.imuframe)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.imuframe)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 1, 1, 3, 1)
        self.comboAddress = QtWidgets.QComboBox(self.imuframe)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboAddress.sizePolicy().hasHeightForWidth())
        self.comboAddress.setSizePolicy(sizePolicy)
        self.comboAddress.setMinimumSize(QtCore.QSize(70, 0))
        self.comboAddress.setBaseSize(QtCore.QSize(30, 0))
        self.comboAddress.setObjectName("comboAddress")
        self.comboAddress.addItem("")
        self.comboAddress.addItem("")
        self.gridLayout.addWidget(self.comboAddress, 2, 0, 1, 1)
        self.verticalLayout_12.addWidget(self.imuframe)
        self.tabSensors.addTab(self.imutab, "")
        self.adc = QtWidgets.QWidget()
        self.adc.setObjectName("adc")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.adc)
        self.verticalLayout_13.setContentsMargins(8, 3, 8, 3)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.adcframe = QtWidgets.QFrame(self.adc)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.adcframe.sizePolicy().hasHeightForWidth())
        self.adcframe.setSizePolicy(sizePolicy)
        self.adcframe.setObjectName("adcframe")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.adcframe)
        self.horizontalLayout_12.setContentsMargins(10, 2, 8, 4)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.checkADCOn = QtWidgets.QCheckBox(self.adcframe)
        self.checkADCOn.setObjectName("checkADCOn")
        self.horizontalLayout_12.addWidget(self.checkADCOn)
        self.comboADCChannel = QtWidgets.QComboBox(self.adcframe)
        self.comboADCChannel.setObjectName("comboADCChannel")
        self.comboADCChannel.addItem("")
        self.comboADCChannel.addItem("")
        self.comboADCChannel.addItem("")
        self.comboADCChannel.addItem("")
        self.horizontalLayout_12.addWidget(self.comboADCChannel)
        self.label_30 = QtWidgets.QLabel(self.adcframe)
        self.label_30.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_30.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_12.addWidget(self.label_30)
        self.comboRangeADC = QtWidgets.QComboBox(self.adcframe)
        self.comboRangeADC.setObjectName("comboRangeADC")
        self.comboRangeADC.addItem("")
        self.comboRangeADC.addItem("")
        self.comboRangeADC.addItem("")
        self.comboRangeADC.addItem("")
        self.comboRangeADC.addItem("")
        self.comboRangeADC.addItem("")
        self.horizontalLayout_12.addWidget(self.comboRangeADC)
        self.label_33 = QtWidgets.QLabel(self.adcframe)
        self.label_33.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_33.setObjectName("label_33")
        self.horizontalLayout_12.addWidget(self.label_33)
        self.comboADCRate = QtWidgets.QComboBox(self.adcframe)
        self.comboADCRate.setObjectName("comboADCRate")
        self.comboADCRate.addItem("")
        self.comboADCRate.addItem("")
        self.comboADCRate.addItem("")
        self.comboADCRate.addItem("")
        self.comboADCRate.addItem("")
        self.comboADCRate.addItem("")
        self.comboADCRate.addItem("")
        self.comboADCRate.addItem("")
        self.horizontalLayout_12.addWidget(self.comboADCRate)
        self.verticalLayout_13.addWidget(self.adcframe)
        self.tabSensors.addTab(self.adc, "")
        self.verticalLayout_3.addWidget(self.tabSensors)
        self.frame_41 = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_41.sizePolicy().hasHeightForWidth())
        self.frame_41.setSizePolicy(sizePolicy)
        self.frame_41.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_41.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_41.setObjectName("frame_41")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_41)
        self.horizontalLayout_13.setContentsMargins(10, 3, 10, 4)
        self.horizontalLayout_13.setSpacing(5)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_31 = QtWidgets.QLabel(self.frame_41)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_31.sizePolicy().hasHeightForWidth())
        self.label_31.setSizePolicy(sizePolicy)
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_13.addWidget(self.label_31)
        self.comboPlot1 = QtWidgets.QComboBox(self.frame_41)
        self.comboPlot1.setObjectName("comboPlot1")
        self.comboPlot1.addItem("")
        self.comboPlot1.addItem("")
        self.comboPlot1.addItem("")
        self.horizontalLayout_13.addWidget(self.comboPlot1)
        self.label_32 = QtWidgets.QLabel(self.frame_41)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_32.sizePolicy().hasHeightForWidth())
        self.label_32.setSizePolicy(sizePolicy)
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_13.addWidget(self.label_32)
        self.comboPlot2 = QtWidgets.QComboBox(self.frame_41)
        self.comboPlot2.setObjectName("comboPlot2")
        self.comboPlot2.addItem("")
        self.comboPlot2.addItem("")
        self.comboPlot2.addItem("")
        self.horizontalLayout_13.addWidget(self.comboPlot2)
        self.verticalLayout_3.addWidget(self.frame_41)
        self.plotFrameOut = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotFrameOut.sizePolicy().hasHeightForWidth())
        self.plotFrameOut.setSizePolicy(sizePolicy)
        self.plotFrameOut.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.plotFrameOut.setFrameShadow(QtWidgets.QFrame.Raised)
        self.plotFrameOut.setObjectName("plotFrameOut")
        self.plotOutLayout = QtWidgets.QVBoxLayout(self.plotFrameOut)
        self.plotOutLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.plotOutLayout.setContentsMargins(0, 0, 0, 0)
        self.plotOutLayout.setSpacing(3)
        self.plotOutLayout.setObjectName("plotOutLayout")
        self.verticalLayout_3.addWidget(self.plotFrameOut)
        self.horizontalLayout.addWidget(self.frame_2)
        self.verticalLayout.addWidget(self.frame)
        self.bInit = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bInit.sizePolicy().hasHeightForWidth())
        self.bInit.setSizePolicy(sizePolicy)
        self.bInit.setObjectName("bInit")
        self.verticalLayout.addWidget(self.bInit)
        self.bLimpar = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bLimpar.sizePolicy().hasHeightForWidth())
        self.bLimpar.setSizePolicy(sizePolicy)
        self.bLimpar.setObjectName("bLimpar")
        self.verticalLayout.addWidget(self.bLimpar)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 986, 26))
        self.menubar.setObjectName("menubar")
        self.menuArquivo = QtWidgets.QMenu(self.menubar)
        self.menuArquivo.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.menuArquivo.setObjectName("menuArquivo")
        self.menuSelecionar_Porta = QtWidgets.QMenu(self.menuArquivo)
        self.menuSelecionar_Porta.setObjectName("menuSelecionar_Porta")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSalvar_dados = QtWidgets.QAction(MainWindow)
        self.actionSalvar_dados.setObjectName("actionSalvar_dados")
        self.actionSair = QtWidgets.QAction(MainWindow)
        self.actionSair.setObjectName("actionSair")
        self.actionCOM1 = QtWidgets.QAction(MainWindow)
        self.actionCOM1.setObjectName("actionCOM1")
        self.actionCOM2 = QtWidgets.QAction(MainWindow)
        self.actionCOM2.setObjectName("actionCOM2")
        self.actionCOM3 = QtWidgets.QAction(MainWindow)
        self.actionCOM3.setObjectName("actionCOM3")
        self.actionCOM4 = QtWidgets.QAction(MainWindow)
        self.actionCOM4.setObjectName("actionCOM4")
        self.actionCOM5 = QtWidgets.QAction(MainWindow)
        self.actionCOM5.setObjectName("actionCOM5")
        self.actionCOM6 = QtWidgets.QAction(MainWindow)
        self.actionCOM6.setObjectName("actionCOM6")
        self.actionCOM7 = QtWidgets.QAction(MainWindow)
        self.actionCOM7.setObjectName("actionCOM7")
        self.actionCOM8 = QtWidgets.QAction(MainWindow)
        self.actionCOM8.setObjectName("actionCOM8")
        self.actionCOM9 = QtWidgets.QAction(MainWindow)
        self.actionCOM9.setObjectName("actionCOM9")
        self.actionCOM10 = QtWidgets.QAction(MainWindow)
        self.actionCOM10.setObjectName("actionCOM10")
        self.actionCOM11 = QtWidgets.QAction(MainWindow)
        self.actionCOM11.setObjectName("actionCOM11")
        self.actionCOM12 = QtWidgets.QAction(MainWindow)
        self.actionCOM12.setObjectName("actionCOM12")
        self.actionUpload = QtWidgets.QAction(MainWindow)
        self.actionUpload.setObjectName("actionUpload")
        self.actionDefineWorkdir = QtWidgets.QAction(MainWindow)
        self.actionDefineWorkdir.setObjectName("actionDefineWorkdir")
        self.actionSavePlus = QtWidgets.QAction(MainWindow)
        self.actionSavePlus.setObjectName("actionSavePlus")
        self.actionWorkdirManager = QtWidgets.QAction(MainWindow)
        self.actionWorkdirManager.setObjectName("actionWorkdirManager")
        self.actionTeste = QtWidgets.QAction(MainWindow)
        self.actionTeste.setObjectName("actionTeste")
        self.menuSelecionar_Porta.addAction(self.actionCOM1)
        self.menuSelecionar_Porta.addAction(self.actionCOM2)
        self.menuSelecionar_Porta.addAction(self.actionCOM3)
        self.menuSelecionar_Porta.addAction(self.actionCOM4)
        self.menuSelecionar_Porta.addAction(self.actionCOM5)
        self.menuSelecionar_Porta.addAction(self.actionCOM6)
        self.menuSelecionar_Porta.addAction(self.actionCOM7)
        self.menuSelecionar_Porta.addAction(self.actionCOM8)
        self.menuSelecionar_Porta.addAction(self.actionCOM9)
        self.menuSelecionar_Porta.addAction(self.actionCOM10)
        self.menuSelecionar_Porta.addAction(self.actionCOM11)
        self.menuSelecionar_Porta.addAction(self.actionCOM12)
        self.menuArquivo.addAction(self.actionSalvar_dados)
        self.menuArquivo.addAction(self.actionUpload)
        self.menuArquivo.addAction(self.menuSelecionar_Porta.menuAction())
        self.menuArquivo.addSeparator()
        self.menuArquivo.addAction(self.actionSavePlus)
        self.menuArquivo.addAction(self.actionDefineWorkdir)
        self.menuArquivo.addAction(self.actionWorkdirManager)
        self.menuArquivo.addSeparator()
        self.menuArquivo.addAction(self.actionSair)
        self.menubar.addAction(self.menuArquivo.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.comboCanal1.setCurrentIndex(0)
        self.comboCanal2.setCurrentIndex(0)
        self.comboCanal3.setCurrentIndex(0)
        self.comboCanal4.setCurrentIndex(0)
        self.tabSensors.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ActVib"))
        self.label_4.setText(_translate("MainWindow", "Tempo no Controlador:"))
        self.elapsedTime.setText(_translate("MainWindow", " 0 s"))
        self.label_5.setText(_translate("MainWindow", "Erro de Tempo:"))
        self.controlTime.setText(_translate("MainWindow", "0 s"))
        self.checkCanal1.setText(_translate("MainWindow", "Ativar 1"))
        self.comboCanal1.setItemText(0, _translate("MainWindow", "Ruído"))
        self.comboCanal1.setItemText(1, _translate("MainWindow", "Senoidal"))
        self.comboCanal1.setItemText(2, _translate("MainWindow", "Chirp"))
        self.label_2.setText(_translate("MainWindow", "Ampl.:"))
        self.label_3.setText(_translate("MainWindow", "Freq.:"))
        self.label_26.setText(_translate("MainWindow", "A2:"))
        self.label_19.setText(_translate("MainWindow", "TI:"))
        self.label_18.setText(_translate("MainWindow", "DI:"))
        self.label_20.setText(_translate("MainWindow", "TF:"))
        self.label_25.setText(_translate("MainWindow", "DF:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.canal1), _translate("MainWindow", "Canal 1"))
        self.checkCanal2.setText(_translate("MainWindow", "Ativar 2"))
        self.comboCanal2.setItemText(0, _translate("MainWindow", "Ruído"))
        self.comboCanal2.setItemText(1, _translate("MainWindow", "Senoidal"))
        self.comboCanal2.setItemText(2, _translate("MainWindow", "Chirp"))
        self.label_6.setText(_translate("MainWindow", "Ampl.:"))
        self.label_7.setText(_translate("MainWindow", "Freq.:"))
        self.label_27.setText(_translate("MainWindow", "A2:"))
        self.label_21.setText(_translate("MainWindow", "TI:"))
        self.label_22.setText(_translate("MainWindow", "DI:"))
        self.label_23.setText(_translate("MainWindow", "TF:"))
        self.label_47.setText(_translate("MainWindow", "DF:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.canal2), _translate("MainWindow", "Canal 2"))
        self.checkCanal3.setText(_translate("MainWindow", "Ativar 3"))
        self.comboCanal3.setItemText(0, _translate("MainWindow", "Ruído"))
        self.comboCanal3.setItemText(1, _translate("MainWindow", "Senoidal"))
        self.comboCanal3.setItemText(2, _translate("MainWindow", "Chirp"))
        self.label_28.setText(_translate("MainWindow", "Ampl.:"))
        self.label_29.setText(_translate("MainWindow", "Freq.:"))
        self.label_35.setText(_translate("MainWindow", "A2:"))
        self.label_36.setText(_translate("MainWindow", "TI:"))
        self.label_37.setText(_translate("MainWindow", "DI:"))
        self.label_38.setText(_translate("MainWindow", "TF:"))
        self.label_39.setText(_translate("MainWindow", "DF:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.canal3), _translate("MainWindow", "Canal 3"))
        self.checkCanal4.setText(_translate("MainWindow", "Ativar 4"))
        self.comboCanal4.setItemText(0, _translate("MainWindow", "Ruído"))
        self.comboCanal4.setItemText(1, _translate("MainWindow", "Senoidal"))
        self.comboCanal4.setItemText(2, _translate("MainWindow", "Chirp"))
        self.label_40.setText(_translate("MainWindow", "Ampl.:"))
        self.label_41.setText(_translate("MainWindow", "Freq.:"))
        self.label_42.setText(_translate("MainWindow", "A2:"))
        self.label_43.setText(_translate("MainWindow", "TI:"))
        self.label_44.setText(_translate("MainWindow", "DI:"))
        self.label_45.setText(_translate("MainWindow", "TF:"))
        self.label_46.setText(_translate("MainWindow", "DF:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.canal4), _translate("MainWindow", "Canal 4"))
        self.comboCanaisControle.setItemText(0, _translate("MainWindow", "C1 - Perturbação, C2 - Controle"))
        self.comboCanaisControle.setItemText(1, _translate("MainWindow", "C1 - Controle, C2 - Perturbação"))
        self.checkControle.setText(_translate("MainWindow", "Ativar"))
        self.comboCanalPerturb.setItemText(0, _translate("MainWindow", "Canal 1"))
        self.comboCanalPerturb.setItemText(1, _translate("MainWindow", "Canal 2"))
        self.comboCanalPerturb.setItemText(2, _translate("MainWindow", "Canal 3"))
        self.comboCanalPerturb.setItemText(3, _translate("MainWindow", "Canal 4"))
        self.label_24.setText(_translate("MainWindow", "Perturbação:"))
        self.label_48.setText(_translate("MainWindow", "Controle:"))
        self.comboRef.setItemText(0, _translate("MainWindow", "0x68 - Acelerômetro X"))
        self.comboRef.setItemText(1, _translate("MainWindow", "0x68 - Acelerômetro Y"))
        self.comboRef.setItemText(2, _translate("MainWindow", "0x68 - Acelerômetro Z"))
        self.comboRef.setItemText(3, _translate("MainWindow", "0x68 - Giroscópio X"))
        self.comboRef.setItemText(4, _translate("MainWindow", "0x68 - Giroscópio Y"))
        self.comboRef.setItemText(5, _translate("MainWindow", "0x68 - Giroscópio Z"))
        self.comboRef.setItemText(6, _translate("MainWindow", "0x69 - Acelerômetro X"))
        self.comboRef.setItemText(7, _translate("MainWindow", "0x69 - Acelerômetro Y"))
        self.comboRef.setItemText(8, _translate("MainWindow", "0x69 - Acelerômetro Z"))
        self.comboRef.setItemText(9, _translate("MainWindow", "0x69 - Giroscópio X"))
        self.comboRef.setItemText(10, _translate("MainWindow", "0x69 - Giroscópio Y"))
        self.comboRef.setItemText(11, _translate("MainWindow", "0x69 - Giroscópio Z"))
        self.label_8.setText(_translate("MainWindow", "Algoritmo:"))
        self.label_16.setText(_translate("MainWindow", "Sensor Ref:"))
        self.comboErro.setItemText(0, _translate("MainWindow", "0x68 - Acelerômetro X"))
        self.comboErro.setItemText(1, _translate("MainWindow", "0x68 - Acelerômetro Y"))
        self.comboErro.setItemText(2, _translate("MainWindow", "0x68 - Acelerômetro Z"))
        self.comboErro.setItemText(3, _translate("MainWindow", "0x68 - Giroscópio X"))
        self.comboErro.setItemText(4, _translate("MainWindow", "0x68 - Giroscópio Y"))
        self.comboErro.setItemText(5, _translate("MainWindow", "0x68 - Giroscópio Z"))
        self.comboErro.setItemText(6, _translate("MainWindow", "0x69 - Acelerômetro X"))
        self.comboErro.setItemText(7, _translate("MainWindow", "0x69 - Acelerômetro Y"))
        self.comboErro.setItemText(8, _translate("MainWindow", "0x69 - Acelerômetro Z"))
        self.comboErro.setItemText(9, _translate("MainWindow", "0x69 - Giroscópio X"))
        self.comboErro.setItemText(10, _translate("MainWindow", "0x69 - Giroscópio Y"))
        self.comboErro.setItemText(11, _translate("MainWindow", "0x69 - Giroscópio z"))
        self.comboAlgoritmo.setItemText(0, _translate("MainWindow", "FxNLMS"))
        self.comboAlgoritmo.setItemText(1, _translate("MainWindow", "FxLMS"))
        self.comboAlgoritmo.setItemText(2, _translate("MainWindow", "FxNLMS Modificado Proposto"))
        self.label_10.setText(_translate("MainWindow", "Parâmetros:"))
        self.label_17.setText(_translate("MainWindow", "Sensor Erro:"))
        self.comboCanalControle.setCurrentText(_translate("MainWindow", "Canal 1"))
        self.comboCanalControle.setItemText(0, _translate("MainWindow", "Canal 1"))
        self.comboCanalControle.setItemText(1, _translate("MainWindow", "Canal 2"))
        self.comboCanalControle.setItemText(2, _translate("MainWindow", "Canal 3"))
        self.comboCanalControle.setItemText(3, _translate("MainWindow", "Canal 4"))
        self.normCtrl.setText(_translate("MainWindow", "1e-4"))
        self.passoCtrl.setText(_translate("MainWindow", "0.01"))
        self.label_12.setText(_translate("MainWindow", "Tam. Memória:"))
        self.label_11.setText(_translate("MainWindow", "Penalização:"))
        self.label_9.setText(_translate("MainWindow", "Passo:"))
        self.checkAlgOn.setText(_translate("MainWindow", "On ≥"))
        self.checkAccX.setText(_translate("MainWindow", "AccX"))
        self.checkGyroX.setText(_translate("MainWindow", "GyroX"))
        self.checkGyroZ.setText(_translate("MainWindow", "GyroZ"))
        self.checkAccY.setText(_translate("MainWindow", "AccY"))
        self.checkGyroY.setText(_translate("MainWindow", "GyroY"))
        self.checkAccZ.setText(_translate("MainWindow", "AccZ"))
        self.label_13.setText(_translate("MainWindow", "AccR:"))
        self.comboGyroRange.setItemText(0, _translate("MainWindow", "±250º/s"))
        self.comboGyroRange.setItemText(1, _translate("MainWindow", "±500º/s"))
        self.comboGyroRange.setItemText(2, _translate("MainWindow", "±1000º/s"))
        self.comboGyroRange.setItemText(3, _translate("MainWindow", "±2000º/s"))
        self.comboAccRange.setItemText(0, _translate("MainWindow", "±2g (±19,6m/s²)"))
        self.comboAccRange.setItemText(1, _translate("MainWindow", "±4g (±39,2m/s²)"))
        self.comboAccRange.setItemText(2, _translate("MainWindow", "±8g (±78,4m/s²)"))
        self.comboAccRange.setItemText(3, _translate("MainWindow", "±16g (±156,9m/s²)"))
        self.comboFilter.setItemText(0, _translate("MainWindow", "260Hz"))
        self.comboFilter.setItemText(1, _translate("MainWindow", "184Hz"))
        self.comboFilter.setItemText(2, _translate("MainWindow", "94Hz"))
        self.comboFilter.setItemText(3, _translate("MainWindow", "44Hz"))
        self.comboFilter.setItemText(4, _translate("MainWindow", "21Hz"))
        self.comboFilter.setItemText(5, _translate("MainWindow", "10Hz"))
        self.comboFilter.setItemText(6, _translate("MainWindow", "6Hz"))
        self.label_15.setText(_translate("MainWindow", "Filter:"))
        self.label_14.setText(_translate("MainWindow", "GyroR:"))
        self.label.setText(_translate("MainWindow", "Address:"))
        self.comboAddress.setItemText(0, _translate("MainWindow", "0x68"))
        self.comboAddress.setItemText(1, _translate("MainWindow", "0x69"))
        self.tabSensors.setTabText(self.tabSensors.indexOf(self.imutab), _translate("MainWindow", "IMU"))
        self.checkADCOn.setText(_translate("MainWindow", "Channel"))
        self.comboADCChannel.setItemText(0, _translate("MainWindow", "1"))
        self.comboADCChannel.setItemText(1, _translate("MainWindow", "2"))
        self.comboADCChannel.setItemText(2, _translate("MainWindow", "3"))
        self.comboADCChannel.setItemText(3, _translate("MainWindow", "4"))
        self.label_30.setText(_translate("MainWindow", "Range:"))
        self.comboRangeADC.setItemText(0, _translate("MainWindow", "±6,144 V"))
        self.comboRangeADC.setItemText(1, _translate("MainWindow", "±4,096 V"))
        self.comboRangeADC.setItemText(2, _translate("MainWindow", "±2,048 V"))
        self.comboRangeADC.setItemText(3, _translate("MainWindow", "±1,024 V"))
        self.comboRangeADC.setItemText(4, _translate("MainWindow", "±0,512 V"))
        self.comboRangeADC.setItemText(5, _translate("MainWindow", "±0,256 V"))
        self.label_33.setText(_translate("MainWindow", "Rate:"))
        self.comboADCRate.setItemText(0, _translate("MainWindow", "8 SPS"))
        self.comboADCRate.setItemText(1, _translate("MainWindow", "16 SPS"))
        self.comboADCRate.setItemText(2, _translate("MainWindow", "32 SPS"))
        self.comboADCRate.setItemText(3, _translate("MainWindow", "64 SPS"))
        self.comboADCRate.setItemText(4, _translate("MainWindow", "128 SPS"))
        self.comboADCRate.setItemText(5, _translate("MainWindow", "250 SPS"))
        self.comboADCRate.setItemText(6, _translate("MainWindow", "475 SPS"))
        self.comboADCRate.setItemText(7, _translate("MainWindow", "860 SPS"))
        self.tabSensors.setTabText(self.tabSensors.indexOf(self.adc), _translate("MainWindow", "ADC"))
        self.label_31.setText(_translate("MainWindow", "Plot 1:"))
        self.comboPlot1.setItemText(0, _translate("MainWindow", "Accelaration"))
        self.comboPlot1.setItemText(1, _translate("MainWindow", "Gyro"))
        self.comboPlot1.setItemText(2, _translate("MainWindow", "ADC"))
        self.label_32.setText(_translate("MainWindow", "Plot 2:"))
        self.comboPlot2.setCurrentText(_translate("MainWindow", "Acceleration"))
        self.comboPlot2.setItemText(0, _translate("MainWindow", "Acceleration"))
        self.comboPlot2.setItemText(1, _translate("MainWindow", "Gyro"))
        self.comboPlot2.setItemText(2, _translate("MainWindow", "ADC"))
        self.bInit.setText(_translate("MainWindow", "Iniciar/Parar"))
        self.bLimpar.setText(_translate("MainWindow", "Limpar Dados"))
        self.menuArquivo.setTitle(_translate("MainWindow", "File"))
        self.menuSelecionar_Porta.setTitle(_translate("MainWindow", "Choose Port"))
        self.actionSalvar_dados.setText(_translate("MainWindow", "Save..."))
        self.actionSair.setText(_translate("MainWindow", "Quit"))
        self.actionCOM1.setText(_translate("MainWindow", "COM1"))
        self.actionCOM2.setText(_translate("MainWindow", "COM2"))
        self.actionCOM3.setText(_translate("MainWindow", "COM3"))
        self.actionCOM4.setText(_translate("MainWindow", "COM4"))
        self.actionCOM5.setText(_translate("MainWindow", "COM5"))
        self.actionCOM6.setText(_translate("MainWindow", "COM6"))
        self.actionCOM7.setText(_translate("MainWindow", "COM7"))
        self.actionCOM8.setText(_translate("MainWindow", "COM8"))
        self.actionCOM9.setText(_translate("MainWindow", "COM9"))
        self.actionCOM10.setText(_translate("MainWindow", "COM10"))
        self.actionCOM11.setText(_translate("MainWindow", "COM11"))
        self.actionCOM12.setText(_translate("MainWindow", "COM12"))
        self.actionUpload.setText(_translate("MainWindow", "Upload secondary and feedback responses..."))
        self.actionDefineWorkdir.setText(_translate("MainWindow", "Define Workdir"))
        self.actionSavePlus.setText(_translate("MainWindow", "Save and Update Metada in Workdir"))
        self.actionWorkdirManager.setText(_translate("MainWindow", "Workdir Manager"))
        self.actionTeste.setText(_translate("MainWindow", "Teste"))
